### ISSUE TITLE
Signed package NuGet

### ISSUE THREAD

**Issue by L3Z4** [hgupta9/FluentFTP#10]
I've seen this part in the build_nuget.bat file :
:: Build signed DLL
rem %msbuild% /p:Configuration=Release /p:SignAssembly=true /p:AssemblyOriginatorKeyFile="%snk%" FluentFTP\FluentFTP.csproj

Is it possible to publish a NuGet package of this library signed ?

**Comment by hgupta9** [comment]
Its possible. I'll do it as time permits.

**Comment by hgupta9** [comment]
Done as of https://github.com/hgupta9/FluentFTP/pull/73. Will be uploaded in next nuget version.
