### ISSUE TITLE
FileExists does not work with mixed slashes

### ISSUE THREAD

**Issue by lucamit** [hgupta9/FluentFTP#102]
Hi,
The file exist method  does not recognize  mixed forward and backward slash present in the path. How ever the same works while downloading and upload method.
For Example: 
Path : \Host\App//file.txt
The above path works in OpenRead,Upload and Download method but fails to work in FileExists method

**Comment by hgupta9** [comment]
Are you using the latest version? FileExists has been updated in 17.0.0. I checked the code and it loosk okay. (GetFtpPath is called internally to cleanup the path)

**Comment by hgupta9** [comment]
Closing this issue since no response was given by OP. If you can answer my question I'll reopen it.
