### ISSUE TITLE
UploadFile seems to return immediately, even with large files

### ISSUE THREAD

**Issue by littlecharva** [hgupta9/FluentFTP#105]
Hi,

I'm calling:

client.UploadFile(localPath, destPath);

But it seems to return immediately, before the file has actually uploaded.  I assumed this method would block the main thread, given that there's an additional UploadFileAsync to run asynchronously?

I want to update a NotifyIcon when the file starts uploading and then again when it's done, but don't want to have to handle the Async methods.

Am I missing something?

**Comment by hgupta9** [comment]
What was the solution?

**Comment by littlecharva** [comment]
Sorry, the solution was to check my code properly before posting - I was updating the NotifyIcon elsewhere in my code which made it look like the method was returning immediately, which is wasn't.

Sorry, I should have posted this instead of just closing it.  Great library by the way - much appreciated.

**Comment by hgupta9** [comment]
@littlecharva Thank you. I hope you have success with your project and the library works out.

**Comment by littlecharva** [comment]
Thanks - I'm going to put the project here on GitHub when it's ready, so I'll drop you a link.
