### ISSUE TITLE
Disable Begin/End async methods for .NET 4.5+ and .NET core

### ISSUE THREAD

**Issue by hgupta9** [hgupta9/FluentFTP#108]
@jblacker Can I disable the Begin/End async methods for .NET 4.5+ and .NET core? It would defined reduce the pollution in the intellisense menu, as currently we have like 4 methods per method:

- Rename()
- RenameAsync()
- BeginRename()
- EndRename()

If we removed these the menus would be cleaner leaving just:

- Rename()
- RenameAsync()

Is there any reason users would prefer the Begin/End system compared to async/await? My implementation is as follows:

```cs
#if (CORE || NETFX45)
		private
#else
		public
#endif
		void EndRename(IAsyncResult ar) {
			GetAsyncDelegate<AsyncRename>(ar).EndInvoke(ar);
		}
```

As you can see I'm just hiding it for the newer platforms, not really disabling it as you are using it internally for async support.

**Comment by jblacker** [comment]
I think it's safer to mark them as depreciated, since that's what most people are used to when a library upgrades so we don't break anyone's project that upgrades.  Then remove the dependency completely on those methods completely by rewriting the async versions as fully async instead of using the wrappers I created.

**Comment by hgupta9** [comment]
But since the. Net 4.5 version is new.... Could we assume no one is using the old async methods?

**Comment by jblacker** [comment]
You make a good point.

**Comment by hgupta9** [comment]
The only problem is if an existing user has already built an app with Begin/End methods and that app uses .NET 4.5, he will have to rewrite it with async/await, and that would be a pain point.

**Comment by hgupta9** [comment]
Closing this since we cannot possibly know if existing users are using the Begin/End methods and therefore hiding them would break their existing code.
