### ISSUE TITLE
Unix-Style symlinks are not parsed correctly.

### ISSUE THREAD

**Issue by UnknownTraveller** [hgupta9/FluentFTP#109]
The space after the arrow seems to be included in the LinkTarget, which results in paths like "/ target_file.txt" (notice the space). This then in turn breaks FtpListOption.DerefLinks, or just calling FtpClient.DereferenceLink(item.LinkTarget) without removing the space manually first.

The relevant changes seem to only be in [FtpListParser.cs  #944 - 947](https://github.com/hgupta9/FluentFTP/blob/master/FluentFTP/FtpListParser.cs#L944). Trimming or skipping an additional character could probably already do the trick (I have not actually tried it).

There is another place where links seem to be parsed ([FtpListParser.ParseUnixList #529](https://github.com/hgupta9/FluentFTP/blob/master/FluentFTP/FtpListParser.cs#L529)), which doesn't seem to have this problem.

This is the line that produced the error:
`lrwxrwxrwx    1 1000     100             9 May 22 18:15 test.link -> test.file`

I just tried the library for the first time, and the parsing seems to have recieved a lot of changes recently, so I don't know how and when each of these functions get called, or if I'm even correct with my guesses, sorry :)

I used the NuGet version, 17.4.0.

**Comment by hgupta9** [comment]
Trimming should solve it right? I'll just trim the LinkTarget wherever it is being set...

**Comment by hgupta9** [comment]
Does this work for you?

- [FluentFTP_17.4.1_BETA.zip](https://we.tl/G46H0sOEyf)

**Comment by UnknownTraveller** [comment]
Sorry, the zip file seems to be broken, but trimming should generally fix it.
Thank you for your quick response!

**Comment by hgupta9** [comment]
That's great. Will be pushed into the next nuget release. Thanks for your detailed error report.
