### ISSUE TITLE
Upload Bytes

### ISSUE THREAD

**Issue by RamonRobben** [hgupta9/FluentFTP#110]
So I was wondering how I go about uploading bytes or a stream of bytes to an FTP server.
Ofcourse I can write the bytes to a file and then upload it with uploadFile but I was just wondering if there is an uploadBytes function or anything since I would like to take printscreens and upload them immediatly instead of writing to a file first.

**Comment by hgupta9** [comment]
Sad that its not obvious, but its [Upload()](https://github.com/hgupta9/FluentFTP#file-transfer) which has overloads for streams/bytes.
