### ISSUE TITLE
Not working with UAP,Version=v10.0.15063?

### ISSUE THREAD

**Issue by IngoBleile** [hgupta9/FluentFTP#113]
Are you planning to make FluentFTP work with UAP, Version=v10.0.15063?

**Comment by hgupta9** [comment]
Please see https://github.com/hgupta9/FluentFTP/issues/112 and https://github.com/hgupta9/FluentFTP/issues/69

**Comment by hgupta9** [comment]
FluentFTP is now compiled for .Net Standard 1.4 and UWP 10.
Can you check and see if it works for your project?

https://www.nuget.org/packages/FluentFTP/

**Comment by IngoBleile** [comment]
I was able to embed and build, looks good, but I have no FTP login to really test it right now. I'll message you later again.

 

 

Gesendet: Donnerstag, 22. Juni 2017 um 11:25 Uhr
Von: "Harsh Gupta" <notifications@github.com>
An: hgupta9/FluentFTP <FluentFTP@noreply.github.com>
Cc: IngoBleile <ingo.bleile@gmx.net>, Author <author@noreply.github.com>
Betreff: Re: [hgupta9/FluentFTP] Not working with UAP,Version=v10.0.15063? (#113)


FluentFTP is now compiled for .Net Standard 1.4 and UWP 10.
Can you check and see if it works for your project?

https://www.nuget.org/packages/FluentFTP/

**Comment by IngoBleile** [comment]
Hi,

 

I am still getting "Could not load file or assembly 'System.Threading.Thread, Version 4.0.0.0 ...'" (see attachment).

 

Thanks

Ingo

 

 

 

Gesendet: Donnerstag, 22. Juni 2017 um 11:25 Uhr
Von: "Harsh Gupta" <notifications@github.com>
An: hgupta9/FluentFTP <FluentFTP@noreply.github.com>
Cc: IngoBleile <ingo.bleile@gmx.net>, Author <author@noreply.github.com>
Betreff: Re: [hgupta9/FluentFTP] Not working with UAP,Version=v10.0.15063? (#113)


FluentFTP is now compiled for .Net Standard 1.4 and UWP 10.
Can you check and see if it works for your project?

https://www.nuget.org/packages/FluentFTP/

**Comment by hgupta9** [comment]
I'll try to remove the dependency on System.Threading.Thread.

**Comment by hgupta9** [comment]
Can you try the latest version on nuget? https://www.nuget.org/packages/FluentFTP/17.5.4

**Comment by IngoBleile** [comment]
You're getting closer, I get an "Operation is not supported on this platform" now (see screenshot).

 

at FluentFTP.FtpClient.AsyncFileExists.BeginInvoke(String path, AsyncCallback callback, Object object)\r\n   
at FluentFTP.FtpClient.BeginFileExists(String path, AsyncCallback callback, Object state)\r\n   
at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1](Func`4 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, Object state, TaskCreationOptions creationOptions)\r\n   
at FluentFTP.FtpClient.<FileExistsAsync>d__404.MoveNext()\r\n
--- End of stack trace from previous location where exception was thrown ---\r\n
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   
at FluentFTP.FtpClient.<UploadFileInternalAsync>d__284.MoveNext()

 

Thanks

Ingo

 

 

 

Gesendet: Montag, 26. Juni 2017 um 17:59 Uhr
Von: "Harsh Gupta" <notifications@github.com>
An: hgupta9/FluentFTP <FluentFTP@noreply.github.com>
Cc: IngoBleile <ingo.bleile@gmx.net>, Author <author@noreply.github.com>
Betreff: Re: [hgupta9/FluentFTP] Not working with UAP,Version=v10.0.15063? (#113)


Can you try the latest version on nuget? https://www.nuget.org/packages/FluentFTP/17.5.4

**Comment by hgupta9** [comment]
Thanks. Can you try using the sync methods and that may work... If you need async you will have to wait until we build support for it....

**Comment by IngoBleile** [comment]
No, it's not working ...

 

 

Gesendet: Montag, 26. Juni 2017 um 20:43 Uhr
Von: "Harsh Gupta" <notifications@github.com>
An: hgupta9/FluentFTP <FluentFTP@noreply.github.com>
Cc: IngoBleile <ingo.bleile@gmx.net>, Author <author@noreply.github.com>
Betreff: Re: [hgupta9/FluentFTP] Not working with UAP,Version=v10.0.15063? (#113)


Thanks. Can you try using the sync methods and that may work... If you need async you will have to wait until we build support for it....

**Comment by hgupta9** [comment]
I've removed the internal locking since it causes issues with async on .NET Std 1.4 / UWP.
Can you check and see if it works for your project?

https://www.nuget.org/packages/FluentFTP/

**Comment by IngoBleile** [comment]
I get a "PermanentNegativeCompletion" now, with

 

 


            var ftp = new FluentFTP.FtpClient(App.FTP_SERVER, App.FTP_PORT, App.FTP_USER, App.FTP_PASSWORD);
            ftp.UploadFile(dbPath, "");

 


 

The FTP server is available.

 

Thanks

Ingo

 

 

Gesendet: Dienstag, 27. Juni 2017 um 16:42 Uhr
Von: "Harsh Gupta" <notifications@github.com>
An: hgupta9/FluentFTP <FluentFTP@noreply.github.com>
Cc: IngoBleile <ingo.bleile@gmx.net>, Author <author@noreply.github.com>
Betreff: Re: [hgupta9/FluentFTP] Not working with UAP,Version=v10.0.15063? (#113)


I've removed the internal locking since it causes issues with async on .NET Std 1.4 / UWP.
Can you check and see if it works for your project?

https://www.nuget.org/packages/FluentFTP/

**Comment by hgupta9** [comment]
I'm closing this since its fixed according to the title.. the lib now works on UAP. If you encounter any more problems please create a new issue.
