### ISSUE TITLE
Do you support FTP commands CCC, PBSZ, PROT?

### ISSUE THREAD

**Issue by northwestfrog** [hgupta9/FluentFTP#116]
The following is only a question.

Let me start by the fact you provide a nice API.
I want to use this API in a context of FTP over explicit TLS.
In the list of supported commands (may be implicit) I did not see the three following commands CCC, PBSZ, PROT. Are these commands supported?

CCC is so the command socket gets unencrypted. Issued after a successful logon. Having it unencrypted allows the connection to an FTP server behind a firewall and having the PORT and PASV commands doctored by the firewall

Also, please provide some details as to the support of certificates that are not fully compliant

Thanks

**Comment by hgupta9** [comment]
Not to my knowledge, but you can always try `ftp.Execute("CCC")` to send any custom command such as [CCC](https://www.smartftp.com/support/kb/clear-command-channel-ccc-f2551.html). To revert back to the insecure way, we'll have to upgrade the FtpClient class to support that.

PBSZ and PROT are automatically sent when you call Connect() and when EncryptionMode and DataConnectionEncryption are set. You can set DataConnectionEncryption to false even when in FTPS, perhaps this is what you are looking for? I'm not the original author of the library so I cannot confirm exactly how it works.  See [this](https://github.com/hgupta9/FluentFTP/blob/master/FluentFTP/FtpClient.cs#L1101).

**Comment by northwestfrog** [comment]
You may want to implement the CCC command (see RFC4217). This removes the encryption from the basic communication channel/socket (as opposed to the DataConection) This would become handy so PORT and PASV commands are visible to a properly configured firewall.
Performing a ftp.Execute("CCC") would irremediably put an end to the communication with the FTP server. The client side would still consider an encrypted communication channel and the server side would consider this to be unencrypted from that point.

**Comment by hgupta9** [comment]
I agree its a good idea, but I don't know how to unencrypt the channel just yet. I'll have to study the source code further.

**Comment by hgupta9** [comment]
I have looked at the code and I think it can be implemented... Are you interested in helping debug it? The API will be client.DisableEncryption().

**Comment by northwestfrog** [comment]
I will be a pleasure to debug this for you

**Comment by hgupta9** [comment]
I tried to support it by sending "CCC" then closing the SSL stream, but after the 200 OK response, the server responds with garbage data. All further commands timeout, whether I send it to the SSL stream or the plaintext stream.

Do you know what happens after the CCC command is sent? What am I supposed to send to th eserver after that? This is a more [complicated explanation of my problem ](https://stackoverflow.com/questions/44456209/how-do-i-disable-encryption-with-the-sslstream-class?noredirect=1#comment75909598_44456209)on SO.

**Comment by northwestfrog** [comment]
Which server is it?

**Comment by hgupta9** [comment]
Pure-FTPd

**Comment by hgupta9** [comment]
I made some progress on this. 

.NET SslStream doesn't close TLS connection properly.
It does not send the close_notify alert before closing the connection.
FTPSslStream uses unsafe code to do that.
This is required when we want to downgrade the connection to plaintext using CCC command.

Thanks to Neco @ https://stackoverflow.com/questions/237807/net-sslstream-doesnt-close-tls-connection-properly/22626756#22626756

**Comment by hgupta9** [comment]
However after I do this the library will contain "unsafe" code.

**Comment by hgupta9** [comment]
Yay! It seems to be working! Can you try this build and confirm if it all goes well on your end?

Please note that only the control connection is unencrypted. The data channel (used by GetListing() and others) continues to be encryp

- [FluentFTP_17.5.0_BETA1.zip](https://we.tl/TBPGcFdijH)

**Comment by hgupta9** [comment]
Here are the logs:
```
# Connect()
Status:   Connecting to ***:21
Response: 220 You will be disconnected after 15 minutes of inactivity.
Response: 220---------- Welcome to Pure-FTPd [privsep] [TLS] ----------
Response: 220-You are user number 1 of 150 allowed.
Response: 220-Local time is now 02:47. Server port: 21.
Response: 220-IPv6 connections are also welcome on this server.
Command:  AUTH TLS
Response: 234 AUTH TLS OK.
Status:   FTPS Authentication Successful
Status:   Time to activate encryption: 0h 0m 0s.  Total Seconds: 0.5850334.
Command:  USER ***
Response: 331 User *** OK. Password required
Command:  PASS ***
Response: 230 OK. Current restricted directory is /
Command:  PBSZ 0
Response: 200 PBSZ=0
Command:  PROT P
Response: 200 Data protection level set to "private"
Command:  FEAT
Response: 211 End.
Response: 211-Extensions supported:
Response: EPRT
Response: IDLE
Response: MDTM
Response: SIZE
Response: MFMT
Response: REST STREAM
Response: MLST type*;size*;sizd*;modify*;UNIX.mode*;UNIX.uid*;UNIX.gid*;unique*;
Response: MLSD
Response: AUTH TLS
Response: PBSZ
Response: PROT
Response: UTF8
Response: TVFS
Response: ESTA
Response: PASV
Response: EPSV
Response: SPSV
Response: ESTP
Status:   Text encoding: System.Text.UTF8Encoding
Command:  OPTS UTF8 ON
Response: 200 OK, UTF-8 enabled
Command:  SYST
Response: 215 UNIX Type: L8
Command:  CCC
Response: 200 Control connection unencrypted
Status:   Auto-detected UNIX listing parser

# GetListing("/public_html/temp/", ForceList, Recursive)
Command:  TYPE I
Response: 200 TYPE is now 8-bit binary

# OpenPassiveDataStream(AutoPassive, "LIST -R /public_html/temp", 0)
Command:  EPSV
Response: 229 Extended Passive mode OK (|||49420|)
Status:   Connecting to ***:49420
The thread '<No Name>' (0x1ab0) has exited with code 0 (0x0).
Command:  LIST -R /public_html/temp
Response: 150 Accepted data connection
Status:   FTPS Authentication Successful
Status:   Time to activate encryption: 0h 0m 0s.  Total Seconds: 0.2520144.
+---------------------------------------+
Listing:  drwxr-xr-x    4 nayidish   nayidish         4096 Jun  7 03:19 .
Listing:  drwxr-x---   19 nayidish   99               4096 May 21 01:53 ..
Listing:  -rw-r--r--    1 nayidish   nayidish        43393 May  3 03:55 Caffè.jpg
Listing:  -rw-r--r--    1 nayidish   nayidish        43393 Apr  1 10:30 Caff�.jpg
Listing:  -rw-r--r--    1 nayidish   nayidish        56985 Jun  7 03:19 README.md
Listing:  -rw-r--r--    1 nayidish   nayidish        30218 Feb 28 00:20 README_moved.md
Listing:  -rw-r--r--    1 nayidish   nayidish     14717504 Feb 22 11:02 big2.txt
Listing:  -rw-r--r--    1 nayidish   nayidish       453546 Mar 10 06:40 file0.exe
Listing:  -rw-r--r--    1 nayidish   nayidish       453546 Mar 10 06:40 file1.exe
Listing:  -rw-r--r--    1 nayidish   nayidish       453546 Mar 10 06:40 file2.exe
Listing:  -rw-r--rw-    1 nayidish   nayidish       453546 Mar 10 06:40 file3.exe
Listing:  -rw-r--r--    1 nayidish   nayidish       453546 Mar 10 06:40 file4.exe
Listing:  drwxr-xr-x    5 nayidish   nayidish         4096 May 21 08:21 php
Listing:  -rw-r--r--    1 nayidish   nayidish       453546 Jan 30 08:26 small.txt
Listing:  drwxr-xr-x    3 nayidish   nayidish         4096 May 15 09:52 spaced folder
Listing:  /public_html/temp/php:
Listing:  drwxr-xr-x    5 nayidish   nayidish         4096 May 21 08:21 .
Listing:  drwxr-xr-x    4 nayidish   nayidish         4096 Jun  7 03:19 ..
Listing:  -rw-r--r--    1 nayidish   nayidish         3775 Apr 23 10:41 basic.html
Listing:  drwxr-xr-x    2 nayidish   nayidish         4096 Apr 23 08:23 js_moved
Listing:  drwxr-xr-x    3 nayidish   nayidish         4096 Apr 23 09:46 php
Listing:  drwxr-xr-x    2 nayidish   nayidish         4096 Apr 23 08:23 test
Listing:  /public_html/temp/php/js_moved:
Listing:  drwxr-xr-x    2 nayidish   nayidish         4096 Apr 23 08:23 .
Listing:  drwxr-xr-x    5 nayidish   nayidish         4096 May 21 08:21 ..
Listing:  -rw-r--r--    1 nayidish   nayidish         2041 Mar 27 20:14 postmessage.html
Listing:  -rw-r--r--    1 nayidish   nayidish          528 Mar 27 20:14 result.html
Listing:  /public_html/temp/php/php:
Listing:  drwxr-xr-x    3 nayidish   nayidish         4096 Apr 23 09:46 .
Listing:  drwxr-xr-x    5 nayidish   nayidish         4096 May 21 08:21 ..
Listing:  -rw-r--r--    1 nayidish   nayidish        55139 Apr 23 10:02 UploadHandler.php
Listing:  drwxr-xr-x    2 nayidish   nayidish         4096 Apr 23 10:47 files
Listing:  -rw-r--r--    1 nayidish   nayidish         1198 Apr 23 10:41 fileupload.php
Listing:  /public_html/temp/php/php/files:
Listing:  drwxr-xr-x    2 nayidish   nayidish         4096 Apr 23 10:47 .
Listing:  drwxr-xr-x    3 nayidish   nayidish         4096 Apr 23 09:46 ..
Listing:  -rw-r--r--    1 nayidish   nayidish     19218358 Apr 23 10:47 20170423221229-124.155.255.8-myarticle-Picatrix (1).pdf
Listing:  -rw-r--r--    1 nayidish   nayidish     19218358 Apr 23 10:45 20170423221229-124.155.255.8-myarticle-Picatrix.pdf
Listing:  -rw-r--r--    1 nayidish   nayidish       777835 Apr 23 10:46 20170423221229-124.155.255.8-myphoto-Penguins (1).jpg
Listing:  -rw-r--r--    1 nayidish   nayidish       777835 Apr 23 10:47 20170423221229-124.155.255.8-myphoto-Penguins (2).jpg
Listing:  -rw-r--r--    1 nayidish   nayidish       777835 Apr 23 10:45 20170423221229-124.155.255.8-myphoto-Penguins.jpg
Listing:  /public_html/temp/php/test:
Listing:  drwxr-xr-x    2 nayidish   nayidish         4096 Apr 23 08:23 .
Listing:  drwxr-xr-x    5 nayidish   nayidish         4096 May 21 08:21 ..
Listing:  -rw-r--r--    1 nayidish   nayidish         7346 Mar 27 20:14 index.html
Listing:  -rw-r--r--    1 nayidish   nayidish        42107 Mar 27 20:14 test.js
Listing:  /public_html/temp/spaced folder:
Listing:  drwxr-xr-x    3 nayidish   nayidish         4096 May 15 09:52 .
Listing:  drwxr-xr-x    4 nayidish   nayidish         4096 Jun  7 03:19 ..
Listing:  -rw-r--r--    1 nayidish   nayidish        30218 Feb 28 00:21 README.md
Listing:  drwxr-xr-x    2 nayidish   nayidish         4096 May 15 09:52 oeuoe
Listing:  -rw-r--r--    1 nayidish   nayidish            0 Feb 28 00:21 zerolen.txt
Listing:  /public_html/temp/spaced folder/oeuoe:
Listing:  drwxr-xr-x    2 nayidish   nayidish         4096 May 15 09:52 .
Listing:  drwxr-xr-x    3 nayidish   nayidish         4096 May 15 09:52 ..
Listing:  -rw-r--r--    1 nayidish   nayidish      3932160 Jan 29 03:48 big2.txt
-----------------------------------------

# CloseDataStream()
Response: 226 49 matches total
Response: 226-Options: -a -l -R
Status:   Disposing FtpSocketStream...
Status:   Confirmed format Unix

# Dispose()
Status:   Disposing FtpClient object...
Command:  QUIT
Response: 221 Logout.
Response: 221-Goodbye. You uploaded 0 and downloaded 0 kbytes.
Status:   Disposing FtpSocketStream...
--DONE--
```

**Comment by northwestfrog** [comment]
Hi,
I downloaded the beta1 zip file and I did not see in the dll the new method (object browser)
Did I miss something?

**Comment by hgupta9** [comment]
I had to use a property instead. See this [FAQ entry](https://github.com/hgupta9/FluentFTP#faq_ccc).

**Comment by northwestfrog** [comment]
Hi,

Your implementation of the CCC is working marvelously.

I am getting the following error on a DownloadFile, and similar error on a GetListing

The FTP server being used is written in c# and it  it is using the same FixedSslStream, with 1 small change: one cannot send the close_notify more than once (boolean flag managed in close method).
BTW, this "FixedSslStream" does not seem to be handling the receiving of a close_notify response...

Other products connecting to this server do not seem to have issue with this server implementation in encrypted mode (WSFTP, Filezilla).

FluentFTP.FtpException was unhandled
  HResult=-2146233088
  Message=Error while downloading the file from the server. See InnerException for more info.
  Source=FluentFTP
  StackTrace:
       à FluentFTP.FtpClient.DownloadFileInternal(String remotePath, Stream outStream) dans d:\Github\hgupta\FluentFTP\FluentFTP\Client\FtpClient_HighLevel.cs:ligne 1721
       à FluentFTP.FtpClient.DownloadFileToFile(String localPath, String remotePath, Boolean overwrite, FtpVerify verifyOptions) dans d:\Github\hgupta\FluentFTP\FluentFTP\Client\FtpClient_HighLevel.cs:ligne 1322
       à FluentFTP.FtpClient.DownloadFile(String localPath, String remotePath, Boolean overwrite, FtpVerify verifyOptions) dans d:\Github\hgupta\FluentFTP\FluentFTP\Client\FtpClient_HighLevel.cs:ligne 1294
       à FTPServerTester.Program.Main(String[] args) dans d:\CoSD\DEV\22-Working\Batch\VisualStudio\Solutions\CoSDSupportSln\FTPServerTester\Program.cs:ligne 43
       à System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       à System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       à Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       à System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       à System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       à System.Threading.ThreadHelper.ThreadStart()
  InnerException: System.ObjectDisposedException
       HResult=-2146232798
       Message=Impossible d'accéder à un objet supprimé.
Nom de l'objet : 'System.Net.Sockets.NetworkStream'.
       Source=System
       ObjectName=System.Net.Sockets.NetworkStream
       StackTrace:
            à System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
            à FluentFTP.SslDirectCall.CloseNotify(SslStream sslStream) dans d:\Github\hgupta\FluentFTP\FluentFTP\Stream\FtpSslStream.cs:ligne 133
            à FluentFTP.FtpSslStream.Close() dans d:\Github\hgupta\FluentFTP\FluentFTP\Stream\FtpSslStream.cs:ligne 43
            à System.IO.Stream.Dispose()
            à FluentFTP.FtpSocketStream.Close() dans d:\Github\hgupta\FluentFTP\FluentFTP\Stream\FtpSocketStream.cs:ligne 604
            à System.IO.Stream.Dispose()
            à FluentFTP.FtpClient.DownloadFileInternal(String remotePath, Stream outStream) dans d:\Github\hgupta\FluentFTP\FluentFTP\Client\FtpClient_HighLevel.cs:ligne 1697
       InnerException:

**Comment by northwestfrog** [comment]
And, then on an upload...

FluentFTP.FtpException was unhandled
  HResult=-2146233088
  Message=Error while uploading the file to the server. See InnerException for more info.
  Source=FluentFTP
  StackTrace:
       à FluentFTP.FtpClient.UploadFileInternal(Stream fileData, String remotePath, Boolean createRemoteDir, FtpExists existsMode, Boolean fileExists, Boolean fileExistsKnown) dans d:\Github\hgupta\FluentFTP\FluentFTP\Client\FtpClient_HighLevel.cs:ligne 1094
       à FluentFTP.FtpClient.UploadFileFromFile(String localPath, String remotePath, Boolean createRemoteDir, FtpExists existsMode, Boolean fileExists, Boolean fileExistsKnown, FtpVerify verifyOptions) dans d:\Github\hgupta\FluentFTP\FluentFTP\Client\FtpClient_HighLevel.cs:ligne 732
       à FluentFTP.FtpClient.UploadFile(String localPath, String remotePath, FtpExists existsMode, Boolean createRemoteDir, FtpVerify verifyOptions) dans d:\Github\hgupta\FluentFTP\FluentFTP\Client\FtpClient_HighLevel.cs:ligne 664
       à FTPServerTester.Program.Main(String[] args) dans d:\CoSD\DEV\22-Working\Batch\VisualStudio\Solutions\CoSDSupportSln\FTPServerTester\Program.cs:ligne 44
       à System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       à System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       à Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       à System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       à System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       à System.Threading.ThreadHelper.ThreadStart()
  InnerException: System.ObjectDisposedException
       HResult=-2146232798
       Message=Impossible d'accéder à un objet supprimé.
Nom de l'objet : 'System.Net.Sockets.NetworkStream'.
       Source=System
       ObjectName=System.Net.Sockets.NetworkStream
       StackTrace:
            à System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
            à FluentFTP.SslDirectCall.CloseNotify(SslStream sslStream) dans d:\Github\hgupta\FluentFTP\FluentFTP\Stream\FtpSslStream.cs:ligne 133
            à FluentFTP.FtpSslStream.Close() dans d:\Github\hgupta\FluentFTP\FluentFTP\Stream\FtpSslStream.cs:ligne 43
            à System.IO.Stream.Dispose()
            à FluentFTP.FtpSocketStream.Close() dans d:\Github\hgupta\FluentFTP\FluentFTP\Stream\FtpSocketStream.cs:ligne 604
            à FluentFTP.FtpDataStream.Close() dans d:\Github\hgupta\FluentFTP\FluentFTP\Stream\FtpDataStream.cs:ligne 161
            à FluentFTP.FtpClient.GetNameListing(String path) dans d:\Github\hgupta\FluentFTP\FluentFTP\Client\FtpClient_Listing.cs:ligne 670
            à FluentFTP.FtpClient.FileExists(String path) dans d:\Github\hgupta\FluentFTP\FluentFTP\Client\FtpClient_Management.cs:ligne 489
            à FluentFTP.FtpClient.UploadFileInternal(Stream fileData, String remotePath, Boolean createRemoteDir, FtpExists existsMode, Boolean fileExists, Boolean fileExistsKnown) dans d:\Github\hgupta\FluentFTP\FluentFTP\Client\FtpClient_HighLevel.cs:ligne 933
       InnerException:

**Comment by hgupta9** [comment]
I'm not getting any errors. This is my code.
```
using (FtpClient client = new FtpClient()) {
	
	client.Credentials = new NetworkCredential(m_user, m_pass);
	client.Host = m_host;
	client.EncryptionMode = FtpEncryptionMode.Explicit;
	client.PlainTextEncryption = true;
	client.SslProtocols = SslProtocols.Tls;
	client.ValidateCertificate += new FtpSslValidation(OnValidateCertificate);
	client.Connect();

	foreach (FtpListItem i in client.GetListing("/public_html/temp/", FtpListOption.ForceList | FtpListOption.Recursive)) {
		//FtpTrace.WriteLine(i);
	}

	// 100 K file
	client.UploadFile(@"D:\Github\FluentFTP\README.md", "/public_html/temp/README.md");
	client.DownloadFile(@"D:\Github\FluentFTP\README2.md", "/public_html/temp/README.md");

}
```

**Comment by hgupta9** [comment]
And please try with this version:

- [FluentFTP_17.5.0_BETA2.zip](https://we.tl/BlkZokbR0d)

**Comment by northwestfrog** [comment]
This second version works very well.

BTW, I saw that if the server only negociates TLS1.1, the client cannot connect. How can we configure FluentFTP to work with TLS 1.1 and TLS 1.2

Best Regards
