### ISSUE TITLE
Minimize round-trips!

### ISSUE THREAD

**Issue by zorgoz** [hgupta9/FluentFTP#12]
Without going deeper and assessing the whole code I have noticed at least one place where the unnecessary round-trips to the server are performed.
Look at `FtpClient.GetListing` method and the `GetListing` example. In the example you suggest passing the current path by calling `GetWorkingDirectory` method (RT1). But when one looks in the code sees that there is a `string pwd = GetWorkingDirectory();` declaration in line 1904, that is making a second round-trip (RT2) regardless of the path parameter, which is still evaluated three lines below and `GetWorkingDirectory` method is either called if necessary.

**Comment by hgupta9** [comment]
Feel free to test/contribute a patch for this.
