### ISSUE TITLE
.NET Core Disable output to Console

### ISSUE THREAD

**Issue by Yannick183** [hgupta9/FluentFTP#125]
Hi,

Is there a way to disable the logging to Console or Debug on the .NET Core version ?

**Comment by hgupta9** [comment]
There is now. Please update your nuget package. And see this for [usage info](https://github.com/hgupta9/FluentFTP#logging).

Does that work for you?

**Comment by Yannick183** [comment]
I don't see the updated NuGet package. The latest version is still 17.5.0

**Comment by hgupta9** [comment]
Sorry, must have been a mistake. I've pushed the latest version now.

**Comment by Yannick183** [comment]
It's all good now! And it's no longer writing to the console. 

Thank you!

**Comment by hgupta9** [comment]
Good to hear that.
