### ISSUE TITLE
PlatformNotSupported Exception in async operations on Linux

### ISSUE THREAD

**Issue by KallDrexx** [hgupta9/FluentFTP#127]
I'm attempting to use this library on the latest stable .Net Core build on Ubuntu Linux, and all Async operations throw a PlatformNotSupported exception.

Unfortunately, this seems to be a fundamental .net core limitation on non-windows platforms (I assume it works on windows since there are VS projects for .net core in there, but I have not actually tested it on Windows).  Essentially the `BeginInvoke` method can't be called on non-windows systems.

For example, the following quick bit of code reproduces the issue: 

```
using System;

namespace test
{
    delegate void SomeDelegate();

    class Program
    {
        static void Main(string[] args)
        {
            var dg = new SomeDelegate(DoSomething);
            dg.BeginInvoke(null, null);
        }

        static void DoSomething()
        {
            Console.WriteLine("Hi");
        }
    }
}
```

I am not totally clear on why you are performing async methods through this mechanisms instead of awaiting the calls up the stack.  I assume it is to reduce code duplication but since could be a pretty big refactor of the code I did not want to just start trying to fix this myself.  

For now I will just have to use the non-async methods since those work just fine.

**Comment by hgupta9** [comment]
The async/await support was added by a contributor on top of the older Begin/End methods. I don't know how to rewrite the methods for true async operations. If you can do one method, like FileExistsAsync (matching FileExists which is synchronous) then I can copy that for all the others.

**Comment by KallDrexx** [comment]
Sounds good.  I'll see if I can get something up and running this weekend.  Playing around in this branch: https://github.com/KallDrexx/FluentFTP/tree/linux-support

**Comment by FloppyNotFound** [comment]
In the first step, you have to get rid of the locking and replace it with something different, like SemaphoreSlim, because async/await is not compatible with locks.

Afterwards, the asnyc code can be introduced.

Maybe I find time for it in the next couple of weeks, but I can't promise anything :(.

**Comment by hgupta9** [comment]
Maybe we can just remove the locking outright for the core version... After all people should not attempt to use one client from many threads and can do their own locking.... Is locking supported on the windows async versions? Then we could detect the platform and disable locking for non windows platforms...

**Comment by KallDrexx** [comment]
Yeah I started looking into this and noticed that the locking would have to be replaced, and then a lot of stuff would have to be rewritten with code duplicated to have proper Async support.  At that point job stuff came up and I didn't really want to do that much surgery on a code base I'm not totally familiar with.

> Maybe we can just remove the locking outright for the core version... After all people should not attempt to use one client from many threads and can do their own locking.... Is locking supported on the windows async versions? Then we could detect the platform and disable locking for non windows platforms...

Locking is supported everywhere, the problem is you cannot `await` from inside a lock scope (the compiler outright rejects this).  Therefore the only way to have synchronization is if you replace the locks with semaphores which do not have that limitation.

**Comment by hgupta9** [comment]
I've removed the internal locking since it causes issues with async on .NET Std 1.4 / UWP.
Can you check and see if it works for your project?

https://www.nuget.org/packages/FluentFTP/

**Comment by miticalex** [comment]
I've check all the async calls on mac, and neither or them worked for me (PlatformNotSupported Exception was thrown)

**Comment by hgupta9** [comment]
Unfortunately until the async methods are completely rewritten this will not be supported on .NET Core.  I guess I'll just disable the async methods from the .NET core build.

**Comment by miticalex** [comment]
Thanks. 
Besides, do the Begin/End calls work? Actually, they've thrown the same exceptions for me.

**Comment by hgupta9** [comment]
No they don't. Which is why in the latest nuget I have disabled all async calls in .net core version. Sorry!
