### ISSUE TITLE
Function logging throwing NullReferenceException

### ISSUE THREAD

**Issue by jmono** [hgupta9/FluentFTP#129]
Hi,

I have an issue with function logging. When trying to run the following code a NullReferenceException is being thrown from GetListing(). I am using v17.5.5 via the NuGet package.
```
using (FtpClient client = new FtpClient(remoteAddress)) {
                client.Credentials = new NetworkCredential(username, password);
                client.Connect();
                FtpListItem[] listing = client.GetListing();
}
```
The stack trace is 
```
   at FluentFTP.FtpExtensions.ItemsToString(Object[] args)
   at FluentFTP.FtpTrace.WriteFunc(String function, Object[] args)
   at FluentFTP.FtpClient.GetListing(String path, FtpListOption options)
   at FluentFTP.FtpClient.GetListing()
```
Setting FtpTrace.LogFunctions = false fixes the NullReferenceException but this is not ideal as I'd like the functions to be logged. 

Thanks

**Comment by hgupta9** [comment]
Wow! The debugging tools have a bug. Good find. I'll fix it asap.

**Comment by hgupta9** [comment]
Can you try the latest version?

https://www.nuget.org/packages/FluentFTP/

**Comment by jmono** [comment]
It works fine now, thanks
