### ISSUE TITLE
Where is the OnLogEvent in 41.1.0?

### ISSUE THREAD

**Issue by Ares-87** [hgupta9/FluentFTP#1313]
**FTP Server OS:** Unix

**Client Computer OS:** Windows

**FluentFTP Version:** 41.1.0

**Framework:** .NET 4

Hi, I come from previous version, where I had configured this code to print into a textarea the verbose logs:
```
client.OnLogEvent = OnFTPLogEvent;
void OnFTPLogEvent(FtpTraceLevel ftpTraceLevel, string logMessage)
  {
      Application.Current.Dispatcher.Invoke(() =>
      {
          textLog.Text += ">> " + logMessage + "\n";
      });
  }
```
Unfortunately the new version updated to 41.1.0 no longer has the event "**OnLogEvent**".
What is the correct way to bind the function with this version?

Thank you in advance.

**Comment by robinrodricks** [comment]
Use `client.LegacyLogger`

Read more: https://github.com/robinrodricks/FluentFTP/wiki/Logging#legacy-logger
