### ISSUE TITLE
How to disable certificate validation

### ISSUE THREAD

**Issue by dmitrynsavin** [hgupta9/FluentFTP#135]
Could you please indicate whether or not there is a way to [disable certificate validation]?
Thanks in advance

**Comment by hgupta9** [comment]
Using the [default FTPS code ](https://github.com/hgupta9/FluentFTP#faq_ftps)will validate any certificate given by the server.

**Comment by dmitrynsavin** [comment]
Have you guys developed any property that switches it to disable? If not -
are you planning so, or I may contribute to this dev?

Tx,
DNS

**Comment by hgupta9** [comment]
I don't know what you mean. Fork it and change whatever you want. Submit a PR, if it looks good, I will accept.
