### ISSUE TITLE
Failed to open file after using DownloadFile

### ISSUE THREAD

**Issue by wernerbarnard** [hgupta9/FluentFTP#143]
Hi,

trying to download a 100MB+ file from a plain FTP server and getting the below error (after listing directory contents and confirming that the file exists)

`FluentFTP.FtpCommandException: Failed to open file.
   at FluentFTP.FtpClient.OpenActiveDataStream(FtpDataConnectionType type, String command, Int64 restart)
   at FluentFTP.FtpClient.OpenDataStream(String command, Int64 restart)
   at FluentFTP.FtpClient.OpenRead(String path, FtpDataType type, Int64 restart)`

What causes this?

I've had many weird errors, such that the directory list returns 0 items when in "AutoActive" mode, but returns 28 items (correct) in AutoPassive.

To download the file, I then disconnect and re-connect to switch to AutoActive, as AutoPassive on downloading gives the following:

`FluentFTP.FtpException: Failed to get the EPSV port from: Switching to ASCII mode.
   at FluentFTP.FtpClient.OpenPassiveDataStream(FtpDataConnectionType type, String command, Int64 restart)
   at FluentFTP.FtpClient.OpenDataStream(String command, Int64 restart)
   at FluentFTP.FtpClient.OpenRead(String path, FtpDataType type, Int64 restart)`

the "FEAT" returns in the tracing for the FTP server:

`Response: 230 Login successful.
Command:  FEAT
Response: 211 End
Response: 211-Features:
Response: EPRT
Response: EPSV
Response: MDTM
Response: PASV
Response: REST STREAM
Response: SIZE
Response: TVFS
Status:   Text encoding: System.Text.UTF8Encoding+UTF8EncodingSealed
Command:  OPTS UTF8 ON
Response: 501 Option not understood.
Command:  SYST
Response: 215 UNIX Type: L8`

I don't own or control the FTP server, but have no issues downloading files in WinSCP or Filezilla, so doubt the issue is there.

**Comment by hgupta9** [comment]
1. Please see the FAQ for tracing, and paste the complete trace/debug logs here for us to analyze.
2. Please paste the complete filezilla logs here for us to compare the behavior

**Comment by wernerbarnard** [comment]
Hi @hgupta9 

Here's the log: (I have deleted IP's and filenames only)

`
Connect()
Status:   Connecting to XXXXXXXX:21
Response: 220 (vsFTPd 2.0.5)
Command:  USER XXXXXXXX
Response: 331 Please specify the password.
Command:  PASS ***
Response: 230 Login successful.
Command:  FEAT
Response: 211 End
Response: 211-Features:
Response: EPRT
Response: EPSV
Response: MDTM
Response: PASV
Response: REST STREAM
Response: SIZE
Response: TVFS
Status:   Text encoding: System.Text.UTF8Encoding+UTF8EncodingSealed
Command:  OPTS UTF8 ON
Response: 501 Option not understood.
Command:  SYST
Response: 215 UNIX Type: L8
Status:   Auto-detected UNIX listing parser

GetListing("/", Auto)
Command:  TYPE I
Response: 200 Switching to Binary mode.

OpenPassiveDataStream(AutoPassive, "LIST /", 0)
Command:  EPSV
Response: 229 Entering Extended Passive Mode (|||43024|)
Status:   Connecting to XXXXXXXX:43024
Command:  LIST /
Response: 150 Here comes the directory listing.
+---------------------------------------+
Listing:  -rw-r--r--    1 5457     1        337236225 Apr 11 08:21 XXXXXXXX.txt
-----------------------------------------
Status:   Disposing FtpSocketStream...
Status:   Confirmed format Unix

DownloadFile("C:\temp\XXXXXXXX.txt", "///XXXXXXXX.txt", True, Delete, OnlyChecksum)

GetFileSize("///XXXXXXXX.txt")
Command:  TYPE I
Response: 226 Directory send OK.
Command:  SIZE /XXXXXXXX.txt
Response: 200 Switching to Binary mode.
Command:  TYPE A
Response: 213 337236225

OpenRead("///XXXXXXXX.txt", ASCII, 0)
Command:  TYPE A
Response: 200 Switching to ASCII mode.

GetFileSize("///XXXXXXXX.txt")
Command:  TYPE I
Response: 200 Switching to ASCII mode.
Command:  SIZE /XXXXXXXX.txt
Response: 200 Switching to Binary mode.
Command:  TYPE A
Response: 213 337236225

OpenPassiveDataStream(AutoPassive, "RETR /XXXXXXXX.txt", 0)
Command:  EPSV
Response: 200 Switching to ASCII mode.
Command:  QUIT
Response: 229 Entering Extended Passive Mode (|||47146|)

Dispose()
Status:   Disposing FtpClient object...
Status:   Disposing FtpSocketStream...
`

I have tried many different settings, including not setting anything specifically, the above is using:
(the important parts)

`
            _ftpClient = new FtpClient(request.Host, request.Port, request.Credentials)
            {
                DataConnectionType = FtpDataConnectionType.AutoPassive,
                Encoding = Encoding.UTF8,
                DownloadDataType = FtpDataType.ASCII,
                SocketKeepAlive = true,
                ListingParser = FtpParser.Machine
            };
            _ftpClient.ValidateCertificate += (control, e) => e.Accept = true;
            _ftpClient.Connect();
            var ftpItems = _ftpClient.GetListing(path);
            return _ftpClient.DownloadFile(localPath, remotePath, overwrite, FtpVerify.OnlyChecksum | FtpVerify.Delete);
`

Filezilla gives the below when successfully downloading a file:

`
Status:	Resolving address of XXXXX
Status:	Connecting to XXXXX:21...
Status:	Connection established, waiting for welcome message...
Status:	Insecure server, it does not support FTP over TLS.
Status:	Server does not support non-ASCII characters.
Status:	Logged in
Status:	Retrieving directory listing...
Status:	Calculating timezone offset of server...
Status:	Timezone offset of server is 0 seconds.
Status:	Directory listing of "/" successful
Status:	Resolving address of XXXXX
Status:	Connecting to XXXXX:21...
Status:	Connection established, waiting for welcome message...
Status:	Insecure server, it does not support FTP over TLS.
Status:	Server does not support non-ASCII characters.
Status:	Logged in
Status:	Starting download of /XXXXX
Status:	File transfer successful, transferred 84 bytes in 1 second
`

This resulted in:

`FluentFTP.FtpException: Error while downloading the file from the server. See InnerException for more info. ---> FluentFTP.FtpException: Failed to get the EPSV port from: Switching to ASCII mode.
   at FluentFTP.FtpClient.OpenPassiveDataStream(FtpDataConnectionType type, String command, Int64 restart)
   at FluentFTP.FtpClient.OpenDataStream(String command, Int64 restart)
   at FluentFTP.FtpClient.OpenRead(String path, FtpDataType type, Int64 restart)`

**Comment by hgupta9** [comment]
Next time you can use FtpTrace.Show* to hide the IPs and stuff...

**Comment by hgupta9** [comment]
And you dont need `FtpVerify.OnlyChecksum | FtpVerify.Delete`, you can just use `FtpVerify.Delete`

**Comment by wernerbarnard** [comment]
Hi,

I have updated to 17.5.9 and it seems to be working now.  Will post back if there's any other issues.

Thanks!

**Comment by wernerbarnard** [comment]
Hi @hgupta9 

Actually, still getting the same error.  It worked 1nce, but without changing anything, getting it again now consistently.

**Comment by wernerbarnard** [comment]
Hi,

Here is an example of the log for the successful transfer.

```
# Connect()
Status:   Connecting to XXXXX:21
Response: 220 (vsFTPd 2.0.5)
Command:  USER YYY
Response: 331 Please specify the password.
Command:  PASS ***
Response: 230 Login successful.
Command:  FEAT
Response: 211 End
Response: 211-Features:
Response: EPRT
Response: EPSV
Response: MDTM
Response: PASV
Response: REST STREAM
Response: SIZE
Response: TVFS
Status:   Text encoding: System.Text.UTF8Encoding+UTF8EncodingSealed
Command:  OPTS UTF8 ON
Response: 501 Option not understood.
Command:  SYST
Response: 215 UNIX Type: L8
Status:   Auto-detected UNIX listing parser

# GetListing("/", Auto)
Command:  TYPE I
Response: 200 Switching to Binary mode.

# OpenPassiveDataStream(AutoPassive, "LIST /", 0)
Command:  EPSV
Response: 229 Entering Extended Passive Mode (|||48562|)
Status:   Connecting to XXXXX:48562
Command:  LIST /
Response: 150 Here comes the directory listing.
+---------------------------------------+
Listing:  -rw-r--r--    1 5457     1        337236225 Apr 11 08:18 XXXXX.txt
-----------------------------------------
Status:   Disposing FtpSocketStream...
Status:   Confirmed format Unix

# DownloadFile("C:\temp\XXXXX.txt", "///XXXXX.txt", True, Delete)

# GetFileSize("///XXXXX.txt")
Status:   There is stale data on the socket, maybe our connection timed out or you did not call GetReply(). Re-connecting...
Status:   The stale data was: 226 Directory send OK.

# Connect()
Status:   Connecting to XXXXX:21
Response: 220 (vsFTPd 2.0.5)
Command:  USER YYY
Response: 331 Please specify the password.
Command:  PASS ***
Response: 230 Login successful.
Command:  FEAT
Response: 211 End
Response: 211-Features:
Response: EPRT
Response: EPSV
Response: MDTM
Response: PASV
Response: REST STREAM
Response: SIZE
Response: TVFS
Status:   Text encoding: System.Text.UTF8Encoding+UTF8EncodingSealed
Command:  OPTS UTF8 ON
Response: 501 Option not understood.
Command:  SYST
Response: 215 UNIX Type: L8
Status:   Auto-detected UNIX listing parser
Command:  TYPE I
Response: 200 Switching to Binary mode.
Command:  SIZE /XXXXX.txt
Response: 213 337236225
Command:  TYPE A
Response: 200 Switching to ASCII mode.

# OpenRead("///XXXXX.txt", ASCII, 0)
Command:  TYPE A
Response: 200 Switching to ASCII mode.

# GetFileSize("///XXXXX.txt")
Command:  TYPE I
Response: 200 Switching to Binary mode.
Command:  SIZE /XXXXX.txt
Response: 213 337236225
Command:  TYPE A
Response: 200 Switching to ASCII mode.

# OpenPassiveDataStream(AutoPassive, "RETR /XXXXX.txt", 0)
Command:  EPSV
Response: 229 Entering Extended Passive Mode (|||1040|)
Status:   Connecting to XXXXX:1040
Command:  RETR /XXXXX.txt
Response: 150 Opening BINARY mode data connection for /XXXXX.txt (337236225 bytes).
Status:   Testing connectivity using Socket.Poll()...
Response: 226 File send OK.
File Verification: PASS
Command:  QUIT
Response: 221 Goodbye.

# Dispose()
Status:   Disposing FtpClient object...
Status:   Disposing FtpSocketStream...
```

**Comment by wernerbarnard** [comment]
Hi @hgupta9 

Any possible feedback or suggestions for me to troubleshoot/resolve this issue?

**Comment by hgupta9** [comment]
1. Try not downloading the file in ASCII. (Remove the `DownloadDataType` line)
2. You have a lot of conflicting settings. (eg server does NOT support UTF and you have specified `Encoding = Encoding.UTF8`)
3. Why do you need machine listings? In most cases the default OS specific parsers should work (remove the `ListingParser = FtpParser.Machine` line)

**Comment by wernerbarnard** [comment]
Hi @hgupta9 

THanks, I have removed those 3 - below is the log, and the error is the same.

```

# Connect()
Status:   Connecting to YYY:21
Response: 220 (vsFTPd 2.0.5)
Command:  USER XYXY
Response: 331 Please specify the password.
Command:  PASS ***
Response: 230 Login successful.
Command:  FEAT
Response: 211 End
Response: 211-Features:
Response: EPRT
Response: EPSV
Response: MDTM
Response: PASV
Response: REST STREAM
Response: SIZE
Response: TVFS
Status:   Text encoding: System.Text.ASCIIEncoding+ASCIIEncodingSealed
Command:  SYST
Response: 215 UNIX Type: L8
Status:   Auto-detected UNIX listing parser

# GetListing("/", Auto)
Command:  TYPE I
Response: 200 Switching to Binary mode.

# OpenPassiveDataStream(AutoPassive, "LIST /", 0)
Command:  EPSV
Response: 229 Entering Extended Passive Mode (|||11822|)
Status:   Connecting to YYY:11822
Command:  LIST /
Response: 150 Here comes the directory listing.
+---------------------------------------+
Listing:  -rw-r--r--    1 5457     1        129361876 Apr 11 08:21 XXX.txt
-----------------------------------------
Status:   Disposing FtpSocketStream...
Status:   Confirmed format Unix

# DownloadFile("C:\temp\XXX.txt", "///XXX.txt", True, Delete)

# GetFileSize("///XXX.txt")
Command:  TYPE I
Response: 226 Directory send OK.
Command:  SIZE /XXX.txt
Response: 200 Switching to Binary mode.
Command:  TYPE A
Response: 213 129361876

# OpenRead("///XXX.txt", Binary, 0)
Command:  TYPE I
Response: 200 Switching to ASCII mode.

# GetFileSize("///XXX.txt")
Command:  SIZE /XXX.txt
Response: 200 Switching to Binary mode.

# OpenPassiveDataStream(AutoPassive, "RETR /XXX.txt", 0)
Command:  EPSV
Response: 213 129361876
Command:  QUIT
Response: 229 Entering Extended Passive Mode (|||14906|)

# Dispose()
Status:   Disposing FtpClient object...
Status:   Disposing FtpSocketStream...
```

Error:
```
Failed to get the EPSV port from: 129361876 | FluentFTP.FtpException: Error while downloading the file from the server. See InnerException for more info. ---> FluentFTP.FtpException: Failed to get the EPSV port from: 129361876
   at FluentFTP.FtpClient.OpenPassiveDataStream(FtpDataConnectionType type, String command, Int64 restart)
```

Options removed:

![image](https://user-images.githubusercontent.com/6905546/28541871-d688ff78-70ba-11e7-9f1f-b2ec8afd8297.png)

**Comment by hgupta9** [comment]
I understand. I'm at a loss for ideas. This typically works in all scenarios. You could try opening the stream yourself and reading the data manually. OpenRead(filepath) to get a stream, read till end, close the stream, then GetReply() after you have closed the stream.

**Comment by wernerbarnard** [comment]
Hi @hgupta9 

That seems to have worked for now.  Here's the code:

![image](https://user-images.githubusercontent.com/6905546/28642576-2c17a388-7253-11e7-8c11-d3c620b2113f.png)

Funny that EPSV doesn't give an error here?  Just downloaded a 130M and 1M file.

Command:  EPSV
Response: 229 Entering Extended Passive Mode (|||40486|)
Status:   Connecting to YYXXYY:40486
Command:  RETR /XXX.txt.Thu
Response: 150 Opening BINARY mode data connection for /XXX.txt.Thu (1243052 bytes).
Status:   Disposing FtpSocketStream...
Command:  QUIT
Response: 226 File send OK.

**Comment by hgupta9** [comment]
Thats great. Maybe some advanced stuff in FileDownloadInternal is causing the bad behavior.

**Comment by hgupta9** [comment]
I'm closing this now since you found a work around. If you do know what the issue or are willing to help fix this in the main DownloadFile method then I'll reopen it.

**Comment by hgupta9** [comment]
@wernerbarnard 

Can you please paste the code as text? I need to add it to the FAQ.

**Comment by wernerbarnard** [comment]
Hi @hgupta9 

```

            // copying remote stream to new local file/stream.
            using (var remoteFileStream = _ftpClient.OpenRead(remotePath, FtpDataType.Binary))
            {
                //remoteFileStream.Seek(0, SeekOrigin.Begin);

                using (var newFileStream = File.Create(localPath))
                {
                    byte[] buffer = new byte[8 * 1024];
                    int len;

                    while ((len = remoteFileStream.Read(buffer, 0, buffer.Length)) > 0)
                    {
                        newFileStream.Write(buffer, 0, len);
                    }
                }
            }
```

**Comment by hgupta9** [comment]
Thank you werner!

**Comment by hgupta9** [comment]
Please call GetReply() at end to read the FTP response. Else there will be other issues. If this does not work for your server then skip it.

**Comment by wernerbarnard** [comment]
Hi @hgupta9 

Me again, regarding this download issue.  i've now found that the download is very inconsistent.  it works, then it doesn't, with the same code.  So me saying it works earlier is one of those "it works" moments.

error:
```
FluentFTP.FtpException

Malformed PASV response: 1498923

FluentFTP.FtpException: Malformed PASV response: 1498923
   at FluentFTP.FtpClient.OpenPassiveDataStream(FtpDataConnectionType type, String command, Int64 restart)
   at FluentFTP.FtpClient.OpenDataStream(String command, Int64 restart)
   at FluentFTP.FtpClient.OpenRead(String path, FtpDataType type, Int64 restart, Boolean checkIfFileExists)
   at FluentFTP.FtpClient.OpenRead(String path)
   at XXX.DownloadFile(String localPath, String remotePath, Boolean overwrite) in XXX.cs:line 113
   at XXX.<ExecuteAsync>d__6.MoveNext() in XXX.cs:line 151
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XXX.<RunAsync>d__2.MoveNext() in XXX.cs:line 41
```

Also getting on OpenRead: (5 minutes later.... for a 500KB file)
```
FluentFTP.FtpCommandException
   at FluentFTP.FtpClient.GetWorkingDirectory()
   at FluentFTP.FtpClient.OpenRead(String path, FtpDataType type, Int64 restart, Boolean checkIfFileExists)
   at FluentFTP.FtpClient.OpenRead(String path)
```

**Comment by XceSx6** [comment]
Dear Developer,

This OpenRead & OpenWrite is really turning into a problem.
I got everything working properly for a while now, but simply trying to Duplicate a file like this throws nothing but Errors.. no matter the FtpDataConnectionType i use..
Always get "Failed to get the EPSV port" or "Malformed PASV response" or something alike.
Mind you, the data was transferred though ..
The file on the other end is complete and works.
