### ISSUE TITLE
Failed to delete a file, if the file name contains Russian letters

### ISSUE THREAD

**Issue by alexanderastanin** [hgupta9/FluentFTP#146]
I try to delete a file with using of

`FtpClient.DeleteFile(file.FullName);`

but I get an error: "FluentFTP.FtpCommandException: Can't find file "?????.xml"".

This problem exists only if file name contains Russian letters. If file name doesn't contain it, then deleting process done successfully.

**Comment by hgupta9** [comment]
We auto switch into unicode if possible, so maybe your server does not support unicode characters. Maybe try setting the connection encoding manually to ensure that special characters work properly:

    client.Encoding = System.Text.Encoding.GetEncoding(1252); // ANSI codepage 1252

Or use whatever codepage you need... this one is for US+European characters... 

I think for Russian you need : [1251 – Windows Cyrillic](https://en.wikipedia.org/wiki/Code_page#Windows_code_pages)

Alternatively [show us the logs ](https://github.com/hgupta9/FluentFTP#faq_trace)to see if UTF support exists on your server.

**Comment by alexanderastanin** [comment]
The problem was solved when I set encoding to 1251. 

Thank you.
