### ISSUE TITLE
Proxy implementation problems

### ISSUE THREAD

**Issue by Zoltan666** [hgupta9/FluentFTP#15]
We've found a number of problems with the proxy implementations:

1. USER@HOST sends the FTP credentials every time instead of the proxy credentials.
2. HTTP 1.1 proxy only connects the base stream correctly. Each stream thereafter is direct to the FTP host, not via the proxy.

I've attached a patch file that addresses these issues. This has been tested on an HTTP 1.1 proxy, but not a USER@HOST proxy.
[fluentftp.txt](https://github.com/hgupta9/FluentFTP/files/627810/fluentftp.txt)

**Comment by hgupta9** [comment]
Typically such changes are best submitted via a PR.

**Comment by Zoltan666** [comment]
Unfortunately, I don't have the time to install and learn the tools to generate a pull request.

**Comment by hgupta9** [comment]
I tried to make sense of your diff using a diffing program, but I was unable to understand which line went where. Can you at least fork my repo and redo your changes on your forked version? To do this:

1. Click **Fork** on the top right
2. Open your version here : https://github.com/Zoltan666/FluentFTP
3. Download [Github Desktop](https://desktop.github.com/) and login to your account
4. Click **+** (top left) then **Clone** and select FluentFTP and click Clone/OK
5. Select a folder on your PC to place the files
6. Edit the files using any editor
7. Click **FluentFTP** on the list (left pane) in Github Desktop
8. Click **Changes** (top)
9. Type a Summary, and click **Commit** (bottom)
10. Click **Sync** (top right)

That's all. It seems a little long but I've included every single step, and its super easy. You shouldn't have to learn anything or use any "tools" apart from GH Desktop.

Hope you can manage that.

**Comment by elmar69** [comment]
Did create that Request with some modifications

**Comment by hgupta9** [comment]
Merged https://github.com/hgupta9/FluentFTP/pull/17. Thanks elmar69 and Zoltan666!
