### ISSUE TITLE
CreateDirectory - Required parameter is null or blank. Parameter name: path

### ISSUE THREAD

**Issue by VaclavRoncka** [hgupta9/FluentFTP#150]
Hi guys,
I have found a bug in 17.5.10 and above versions (previous versions works fine) when creating directory:
"Required parameter is null or blank. Parameter name: path" - but i have provided path!
   at FluentFTP.FtpClient.DirectoryExists(String path)
   at FluentFTP.FtpClient.CreateDirectory(String path, Boolean force)
   at FluentFTP.FtpClient.CreateDirectory(String path)

**Comment by hgupta9** [comment]
I fixed it in 17.6.1.

**Comment by hgupta9** [comment]
https://www.nuget.org/packages/FluentFTP/17.6.1

**Comment by VaclavRoncka** [comment]
Thank you hgupta9.
17.6.1 tested - works fine! 👍

**Comment by hgupta9** [comment]
Great news.
