### ISSUE TITLE
Upload or download in multiple concurrent sessions.

### ISSUE THREAD

**Issue by myogendra** [hgupta9/FluentFTP#151]
Hello,

How to create multiple concurrent sessions in FluentFTP for upload and download, I am trying to open connection while iterating through fileSystemInfo within TASK with five concurrent threads at one time. But I think this one is not a valid one can anyone help me.

Thanks.

**Comment by hgupta9** [comment]
Try using a BackgroundWorker. Create a FluentFTP in each worker. It should work.

**Comment by hgupta9** [comment]
Or you can use async/await keywords in NET Framework version for async support. Create multiple FluentFTP Client instances.

**Comment by myogendra** [comment]
Hi,

I am getting an exceptions while doing upload in concurrent sessions,
" Error while uploading the file to the server. See InnerException for more info.
System.InvalidOperationException: You cannot modify the position of a FtpDataStream. This property is updated as data is read or written to the stream."
Could you please help me out to figure out the issue and possible solution for this.

what could be the issue, I am attaching FTP server logs for more clarity.

Here is my code:
`public void UploadFiles(string sourcePath, string remotePath)
        {
            FtpClient client = null;
            try
            {
                CancellationTokenSource cancellationToken = new CancellationTokenSource();

                var fileSystemInfos = new DirectoryInfo(sourcePath).EnumerateFileSystemInfos("*", SearchOption.AllDirectories);
                Uri uriPath = new Uri(sourcePath);

                List<Task> taskList = new List<Task>();

                Stopwatch sw = new Stopwatch();
                sw.Start();
                foreach (var fileInfo in fileSystemInfos)
                {
                    var relativePath = Uri.UnescapeDataString(uriPath.MakeRelativeUri(new Uri(Path.GetFullPath(fileInfo.FullName))).ToString());
                    var remoteRelativePath = string.Concat(remotePath, "/" + relativePath.Replace("../", "/"));

                    Task task = Task.Factory.StartNew( () =>
                        {
                            try
                            {
                                FtpConnectionManager.ConnectToFTP(out client);
                                if (fileInfo.Attributes == FileAttributes.Directory)
                                {
                                    client.SetWorkingDirectory(relativePath);
                                }
                                else
                                {
                                    Console.WriteLine(DateTime.Now + "  Transfer of file " + remoteRelativePath +
                                                      " started " + Environment.NewLine);
                                    Trace.WriteLine(DateTime.Now + "  Transfer of file " + remoteRelativePath +
                                                    " started " + Environment.NewLine);
                                    client.TransferChunkSize = 10000;
                                    client.UploadDataType = FtpDataType.Binary;
                                    client.RetryAttempts = 5;

                                    bool fileUploaded = client.UploadFile(fileInfo.FullName, remoteRelativePath, FtpExists.Append, true, FtpVerify.Retry | FtpVerify.Delete);

                                    if (fileUploaded)
                                    {
                                        Console.WriteLine(DateTime.Now + "  Transfer of file " + remoteRelativePath +
                                                          " done" + Environment.NewLine);
                                        Trace.WriteLine(DateTime.Now + "  Transfer of file " + remoteRelativePath +
                                                        " done" + Environment.NewLine);
                                    }
                                }

                            }
                            catch (Exception ex)
                            {
                                Trace.WriteLine(DateTime.Now.ToString(CultureInfo.InvariantCulture) +
                                                "Error in Uploading file " + remoteRelativePath + " " + ex.Message +
                                                Environment.NewLine + ex.InnerException + Environment.NewLine +
                                                ex.StackTrace);
                            }
                            finally
                            {
                               client?.Disconnect();
                            }
                        }, cancellationToken.Token, TaskCreationOptions.AttachedToParent,
                        _taskScheduler);
                    taskList.Add(task);
                }
                Task.WaitAll(taskList.ToArray(), cancellationToken.Token);
              
                sw.Stop();
                client.Dispose();
                Console.WriteLine(DateTime.Now + "  Time took to upload " + sw.ElapsedMilliseconds);
                Trace.WriteLine(DateTime.Now + "  Time took to upload " + sw.ElapsedMilliseconds);
            }
            catch (Exception ex)
            {
                Trace.WriteLine(DateTime.Now.ToString(CultureInfo.InvariantCulture) + "Error in Uploading file " + " " + ex.Message + Environment.NewLine + ex.InnerException + Environment.NewLine + ex.StackTrace);
            }
        }
`

[log_file.txt](https://github.com/hgupta9/FluentFTP/files/1193538/log_file.txt)

**Comment by myogendra** [comment]
Also I am getting below error in disconnect.
when I am disconnecting ftpSession in Finally block 
"Timed out trying to read data from the socket stream!"

**Comment by hgupta9** [comment]
You have to create a new ftp client instance per async thread. You cannot create one client and use it from all the threads at one time. Obviously that won't work. Even with async/await syntax.

**Comment by hgupta9** [comment]
I think you should create a new client at this line : FtpConnectionManager.ConnectToFTP(out client);

**Comment by myogendra** [comment]
Thanks, its working now, I am creating new ftpClient instance per async thread.
