### ISSUE TITLE
Example Usage code incorrect

### ISSUE THREAD

**Issue by likuilin** [hgupta9/FluentFTP#154]
The Example Usage in readme.md says: 

```
// create an FTP client
FtpClient client = new FtpClient("123.123.123.123");

// if you don't specify login credentials, we use the "anonymous" user account
client.Credentials = new NetworkCredential("david", "pass123");

// begin connecting to the server
client.Connect();
```

This isn't correct currently, FtpClient doesn't take arguments (I'm guessing it used to but not anymore). Instead, it should be:

```
// create an FTP client
FtpClient client = new FtpClient();

// set the host address
client.Host = "123.123.123.123";

// if you don't specify login credentials, we use the "anonymous" user account
client.Credentials = new NetworkCredential("david", "pass123");

// begin connecting to the server
client.Connect();
```

(I don't use Git much at all so I apologize in advance if this is in any way an incorrect way to report this)

Edit: `client.RetryAttempts = 3;` is also outdated.

**Comment by hgupta9** [comment]
You may be using an older version. Everything compiles fine for me. Grab the latest off nuget, the releases section is horribly outdated.

https://www.nuget.org/packages/FluentFTP/

**Comment by hgupta9** [comment]
Are you using the .NET core version?
