### ISSUE TITLE
MFMT command is not setting time properly

### ISSUE THREAD

**Issue by myogendra** [hgupta9/FluentFTP#159]
I am executing a low level command after each file upload
 client.Execute("MFMT " + file.LastWriteTime.ToString("yyyyMMddHHmmss") + " " +                                                    remoteRelativePath);
It is setting Date properly, but for time it is changing the value, while debug I have seen that date time string which I am passing to the command is not setting it is setting some other value. 

**I have to preserve date time of the file to the local date time, so that if there is any new files coming in at Source or if there is any changes in existing files which have uploaded could be syncUp with the Ftp (destination) server while I trigger Syncronization between source and destination.**

In log it is showing proper value
Status:   Connecting to 157.237.219.95:58662
Response: 226 Successfully transferred "/UploadFolder/Upload1/1401.data" 
Response: 221 Goodbye
Command:  MFMT 20170411135458 /UploadFolder/Upload1/1401.data
Status:   Disposing FtpSocketStream...
Command:  STOR /UploadFolder/Upload1/New folder/1404.data
Response: 213 modify=20170411135458; /UploadFolder/Upload1/1401.data

**Comment by myogendra** [comment]
I have converted my datetime to UTC and it is working fine now, So I am closing this query.

**Comment by hgupta9** [comment]
In the latest version there is a new SetModifiedTime API to change modified date of a server file in local timezone/UTC. Can you check it and see if it works for you??

https://www.nuget.org/packages/FluentFTP/

**Comment by myogendra** [comment]
With the latest version of FluentFtp it's working fine,

**Comment by hgupta9** [comment]
Thats great, thanks.
