### ISSUE TITLE
Getting Login Errors but works fine when opening in Firefox

### ISSUE THREAD

**Issue by namigop** [hgupta9/FluentFTP#16]
Hi Guys,

I'm trying to get directory listing of this : site ftp://163.25.117.117/chingter/ and I'm getting a Login Incorrect error

> 
> An exception of type 'FluentFTP.FtpCommandException' occurred in FluentFTP.dll but was not handled in user code
> 
> Additional information: Login incorrect.

This is my code
` use conn = new FtpClient()           
                conn.Host <- uri.Host;
                conn.Credentials <- new NetworkCredential("someuser","")
                conn.EncryptionMode <- FtpEncryptionMode.None;
                conn.SetWorkingDirectory(uri.PathAndQuery)
                //conn.Credentials <- new NetworkCredential("ftptest", "ftptest");
                let listings = conn.GetListing()`
  
When I open the same FTP url in firefox, it is able to display the listing.  I think I'm missing something obvious.  Help, please?

**Comment by hgupta9** [comment]
Your URL seems to be not an FTP server. I tried connecting with FileZilla but it says :+1: 
> **Response:**	530 Login incorrect.
> **Error:**	Critical error: Could not connect to server

**Comment by hgupta9** [comment]
I reopened this issue because there maybe an improvement possible in `GetListing`.

**Comment by hgupta9** [comment]
Thanks for the easy to test example!

I reproduced the error on my PC, and since it connected fine with FileZilla, I attempted to duplicate FileZilla's behaviour in this matter.

Use this code:

```csharp
using (FtpClient cl = new FtpClient()) {
	cl.Host = "163.25.117.117";
	cl.DataConnectionType = FtpDataConnectionType.PASV;
	cl.Connect();

	foreach (FtpListItem item in cl.GetListing("/chingter/")) {
		//Console.WriteLine(item.FullName);
	}
}
```

Please use the latest version of FluentFTP pushed to nuget.
