### ISSUE TITLE
IFtpClient not included in projects

### ISSUE THREAD

**Issue by Lukazoid** [hgupta9/FluentFTP#166]
Commit 75eb65cdf1c5e7eb8c298cb4b3464f76f175360c added an IFtpClient interface which FtpClient implements, however this interface has not been included in any of the projects, this means the projects do not currently build.

**Comment by Lukazoid** [comment]
This may only affect FluentFTP.csproj

**Comment by hgupta9** [comment]
Published to nuget - https://www.nuget.org/packages/FluentFTP/18.0.1
