### ISSUE TITLE
Server Reply Not Read on FtpDataStream Dispose

### ISSUE THREAD

**Issue by Lukazoid** [hgupta9/FluentFTP#167]
This looks like it is related to issue #53 but occurs when running on the full .NET framework.

I first noticed this when attempting multiple uploads on one `FtpClient`, on some subsequent uploads I noticed the following trace messages:

> Command: TYPE I
> Response: 226 Transfer complete.

This looks like the server reply is not being read when an `FtpDataStream` is disposed.

When disposing of an `FtpDataStream` the call flow currently looks like:
> FtpSocketStream.Dispose() (due to shadowing IDisposable.Dispose()) -> FtpSocketStream.Close()

This means that `FtpDataStream.Close()` never gets called and thus `ControlConnection.CloseDataStream` is never called and no server reply read.

**Comment by hgupta9** [comment]
Thank you for this notice. Yes I know, but the person who informed me before refused to help fix it. Thank you for fixing it!

**Comment by hgupta9** [comment]
Published to nuget - https://www.nuget.org/packages/FluentFTP/18.0.1

**Comment by canhantas** [comment]
I am still experiencing this exact problem after updating to 18.0.1

**Comment by Lukazoid** [comment]
Is that using the `Upload`/`Download` methods? I've not used those so didn't realise this workaround existed in those.

I'll do some further testing today but we may be able to remove those blocks of code as the `FtpDataStream` should now handle reading the final reply itself.
