### ISSUE TITLE
Having issues with how to get data transmission speed 

### ISSUE THREAD

**Issue by qixuxiang** [hgupta9/FluentFTP#182]
I want to make a progress bar when I upload or download file with FluentFTP,Does FluentFTP have any API or function to get data transmission speed when transferring files?

**Comment by hgupta9** [comment]
You mean progress tracking. Not transmission speed. There was an idea for this in #91 but not implemented yet. I think there is a way you can do this by using a stream for upload/download and then seeing bytes transferred on the steam. Check that issue for the implementation. If you don't find it, write back.

**Comment by hgupta9** [comment]
Closing this as it's a duplicate. Please add your notes into #91

**Comment by robinrodricks** [comment]
Implemented progress tracking via IProgress for Upload/Download/UploadFile/DownloadFile.
The callback will be called with a number from 0 to 100, based on the percentage of completion.

Please grab it at : https://www.nuget.org/packages/FluentFTP/19.1.0

**Comment by qixuxiang** [comment]
awesome！！！thx a lot!
