### ISSUE TITLE
UWP System.IO.FileNotFoundException

### ISSUE THREAD

**Issue by taoyouh** [hgupta9/FluentFTP#185]
When trying to connect in a UWP app, the following error occurs: 

> "Could not load file or assembly 'System.Console, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'"

Code:
```
FluentFTP.FtpTrace.EnableTracing = false;
FluentFTP.FtpClient conn = new FluentFTP.FtpClient();
conn.Host = "{IP address}";
conn.Connect();
```

Exception throws at "conn.Connect();"

Version: NuGet 18.0.2

**Comment by taoyouh** [comment]
After adding NuGet package System.Console to the UWP project, exception no longer occurs.

**Comment by artiomchi** [comment]
Interesting catch. If you need logging to console, you'll of course need the System.Console package.

If you don't need it, you could set LogToConsole to false.

I think it would be much better for the project to log (or add the ability to log) to `Trace` instead though :)

**Comment by taoyouh** [comment]
Even though LogToConsole is set to false, error occurs.

**Comment by taoyouh** [comment]
Shall we add System.Console to NuGet dependencies?

**Comment by artiomchi** [comment]
Funny thing is, the Console reference seems only to be used when using .NET Standard anyway.

I've added a patch for it in my PR (#190), hopefully the author will come back soon to work on the project :)
