### ISSUE TITLE
File download hangs (inconsistently) when reading data from stream

### ISSUE THREAD

**Issue by artiomchi** [hgupta9/FluentFTP#188]
We're downloading over 5K files from various servers in one process, and several times now the download process just hung. I've taken a process dump, and I can see that it hangs while trying to read from the remote stream:
![image](https://user-images.githubusercontent.com/822898/30479755-9814d852-9a0e-11e7-8085-961ed9c7c6a5.png)

My guess is this is related to #174, and so far I'm testing an extended version of his fix from #175. The problem is that the issue is inconsistent and hard to reproduce, so the only way to know if the fix **doesn't** work if it fails after applying it. 

I'll have our custom build running for several days, and will report early next week if the issue has reappeared, or if the fix actually takes care of the issue

**Comment by hgupta9** [comment]
Thank you!!

**Comment by artiomchi** [comment]
So far we haven't had any issues, and the downloads are coming in like a dream! The patch did the job, so I'm closing this issue :)

**Comment by robinrodricks** [comment]
Wow! You discovered the issue and then fixed it yourself! Great job!

**Comment by artiomchi** [comment]
Thanks! :)

And many thanks to @bgroenks96 for noticing the issue with the uploads in the first place, as well as reviewing and improving my patch!
