### ISSUE TITLE
Invalid HTTP version when using a proxy

### ISSUE THREAD

**Issue by farnsy** [hgupta9/FluentFTP#22]
I am trying to fit an FTP server from behind a firewall. Initially I specified the proxy address as "http://<server>" and port as 3128, however I was then getting an exception from System.Net "No such host" and it appeared that the proxy wasn't being used. Checking the proxy tests, I realised it was my bad and I removed the http://. 

However, now I'm getting 

Can't connect ftp.bom.gov.au via proxy <ip address. Message : FluentFTP.FtpReply.

Checking the squid cache.log (v2.7, running on windows) I'm seeing:

2016/12/16 10:41:14| clientTryParseRequest: FD 19 (<ip>:<port>) Invalid Request
2016/12/16 10:51:08| parseHttpRequest: Invalid HTTP version

Any tips on how this can be resolved?

Thanks for any help you're able to provide.

**Comment by hgupta9** [comment]
I've just pushed a new version to nuget which contains some fixes for proxies. Can you update your FluentFTP and try again to see if the errors persist?

**Comment by farnsy** [comment]
Great! Have tested this morning and can confirm I was able to connect through the proxy and upload a file as expected. 

Thanks for your great work.

**Comment by hgupta9** [comment]
Excellent! I'll close the issue then.
