### ISSUE TITLE
SFTP support?

### ISSUE THREAD

**Issue by mirhagk** [hgupta9/FluentFTP#23]
As far as I can tell it isn't support, but issue #4 suggests that there is SFTP support?

Either way the readme should probably mention it (either that it's supported or not supported) just to clear things up

**Comment by hgupta9** [comment]
As I'm not the original author of the lib, I don't know for sure. But FTP through SSL is definitely supported. There is some confusion between SFTP and FTPS, both being different protocols/methods.

**Comment by mirhagk** [comment]
Yes for sure there is confusion. As far as I can tell the library doesn't support SFTP (which is FTP over SSH), I've tried to make it work and it fails, and looks like the original project maintainer confirmed that [it did not support SFTP as of Mar 2013](https://netftp.codeplex.com/workitem/370).

Because of the confusion around this there should definitely be something in the readme (or at least in an FAQ or something) that says SFTP, that is FTP over SSH, is not supported while FTPS, that is FTP over SSL is supported.

**Comment by Zoltan666** [comment]
From https://en.wikipedia.org/wiki/SSH_File_Transfer_Protocol :
"SFTP is not FTP run over SSH, but rather a new protocol designed from the ground up by the IETF SECSH working group."

**Comment by Zoltan666** [comment]
If you need SFTP support, this library will do it: https://github.com/sshnet/SSH.NET

**Comment by mirhagk** [comment]
Ah okay, but yeah the readme or something should clarify that this does not have SFTP support on the home page. At least mentioning what protocols are supported. I'm sure I'm not the only one to confuse all the different FTP related protocols

**Comment by hgupta9** [comment]
@mirhagk - Good idea. Readme has been updated. Check it out!

**Comment by mirhagk** [comment]
Awesome 👍 Very clear and helpful
