### ISSUE TITLE
Access is Denied when do upload with Explicit SSL

### ISSUE THREAD

**Issue by kilalas** [hgupta9/FluentFTP#25]
I have problem when to upload file from local to ftp server. 
Below is my code to upload the files to the ftp server and an error shows 'Access is Denied'. Anybody have solutions? Thanks in advance.

![capture](https://cloud.githubusercontent.com/assets/24729700/21449248/2a4d42be-c926-11e6-9344-c0e3ee2b631f.JPG)

**Comment by hgupta9** [comment]
Can you provide your login details in order for me to test? If not then can you create a test FTP account on your server and provide that? Its really difficult to debug such use-case issues without connecting to the actual server. You could just add a comment with it, and delete the comment immediately after. I will get the details by email. I will need the server hostname/IP, the user name and the password.

**Comment by hgupta9** [comment]
I'm closing this since you haven't provided any more data for a week. Write back if you want to continue this issue and I'll reopen it.
