### ISSUE TITLE
GetListing with spaces in path

### ISSUE THREAD

**Issue by raboud** [hgupta9/FluentFTP#27]
GetListing("/usr/local/plexdata/Plex Media Server") returns nothing...
GetListing("/usr/local/plexdata") returns correct data

i have manually ftped to server and verified i can see the underlying directories and files
server is a freebsd box

**Comment by hgupta9** [comment]
Can you try with `GetListing("/usr/local/plexdata/Plex%20Media%20Server")` and tell me if it works? I can then add some URL escaping logic to GetListing.

**Comment by raboud** [comment]
Does not help.

I’ll pull the library today and try and debug it.

In the mean time I reverted to just using FtpWebRequest and doing it the hard way.

**Comment by hgupta9** [comment]
@raboud - You forgot to add the '/' at the end. I tested uploading with this and it worked:

     GetListing("/usr/local/plexdata/Plex Media Server/")

I tested `UploadFile`, `DownloadFile` and the lot and they all work fine provided the slash is a postfix.

**Comment by raboud** [comment]
did you try against a FreeBSD server. I did try with the terminating slash. I've retested tonight and still no joy.

**Comment by raboud** [comment]
and did you try GetListing

**Comment by raboud** [comment]
Did you try against a freebsd server and did you try GetListing.
I did try with a / at the end, but for the sake of completeness I retested tonight….still no joy.
It worked for other directories but NONE with a space in the name.

**Comment by hgupta9** [comment]
Can you please try with this:

    GetListing("/usr/local/plexdata/Plex+Media+Server/")

**Comment by hgupta9** [comment]
I've upgraded the GetListing() file listing parser to include OS-specific parsers. This may resolve your issue. If you are interested in helping debug this, then please use this beta build and give me feedback: 

- [FluentFTP_16.6_BETA.rar](https://we.tl/YiWHrDYJxq)

**Comment by hgupta9** [comment]
All new features released on nuget : https://www.nuget.org/packages/FluentFTP/

**Comment by hgupta9** [comment]
Closing this since no response received from OP.
