### ISSUE TITLE
OpenRead always retuns size 0

### ISSUE THREAD

**Issue by guido-gtt** [hgupta9/FluentFTP#28]
When I try to download a file using FluentFTP the OpenRead always returns a stream with size 0
What could be the cause for this ? The files are there and I can download them with filezilla or total commander so there is no security problem or anything

here is my code

                FtpClient client = new FtpClient();
                client.Host = drv["Host"].ToString();
                client.Port = (int)drv["Port"];
                client.Credentials = new NetworkCredential(drv["UserName"].ToString(), drv["PassWord"].ToString());
                client.EnableThreadSafeDataConnections = false; // the ftp server only allows one connection per username
                client.Connect();

                client.SetWorkingDirectory(remoteDir); // GetListing with a folder does not works

                    using (Stream stream = client.OpenRead(remoteFile))
                    {
                         SaveStreamToFile(localFile, stream);
                    }

        private void SaveStreamToFile(string fileFullPath, Stream stream)
        {
            if (stream.Length == 0) 
                  return; // I always get here. Why ????????

            // Create a FileStream object to write a stream to a file
            using (FileStream fileStream = System.IO.File.Create(fileFullPath, (int)stream.Length))
            {
                // Fill the bytes[] array with the stream data
                byte[] bytesInStream = new byte[stream.Length];
                stream.Read(bytesInStream, 0, (int)bytesInStream.Length);

                // Use FileStream object to write to the specified file
                fileStream.Write(bytesInStream, 0, bytesInStream.Length);
            }
        }

**Comment by hgupta9** [comment]
Can you provide your login details in order for me to test? If not then can you create a test FTP account on your server and provide that? Its really difficult to debug such use-case issues without connecting to the actual server. You could just add a comment with it, and delete the comment immediately after. I will get the details by email.

**Comment by guido-gtt** [comment]
After strugling with this all day I tested another ftp library which does not has this problem, so I am going to switch to that library.
Sorry but this library is just not stable enough for me.

**Comment by hgupta9** [comment]
I added a high level API for `client.DownloadFile`. If you wish to check it out you may.

And which library did you find that works better? I myself use FTP in my apps so I would like to know.

**Comment by guido-gtt** [comment]
Currently I am using this one
http://enterprisedt.com/products/edtftpnet/

It worked straight from my first try and my code is 4 times smaller
I have it in production only one day yet so still to wait if any problems can occur, but until know my logs are clear from exceptions and all files where downloaded.
I use it in a windows service.


Van: Harsh Gupta [mailto:notifications@github.com]
Verzonden: vrijdag 6 januari 2017 6:29
Aan: hgupta9/FluentFTP <FluentFTP@noreply.github.com>
CC: Guido <Guido@gtt-carcarriers.com>; Author <author@noreply.github.com>
Onderwerp: Re: [hgupta9/FluentFTP] OpenRead always retuns size 0 (#28)


I added a high level API for client.DownloadFile. If you wish to check it out you may.

And which library did you find that works better? I myself use FTP in my apps so I would like to know.

**Comment by hgupta9** [comment]
Thanks for the info!
