### ISSUE TITLE
Nuget

### ISSUE THREAD

**Issue by imperugo** [hgupta9/FluentFTP#3]
Hi, 
is FluentFTP available on Nuget?

Looking the code it seems you have the scripts to create the nuget packaged, but I can't find it.

Thanks
.u

**Comment by hgupta9** [comment]
I'm setting up a MyGet system this week.

**Comment by imperugo** [comment]
Thanks.
Let me know when is on Nuget.

**Comment by oquirion** [comment]
I've just installed it through NuGet and it worked like a charm (good timing bu the way ;-).
Is there a way to bundle an X509 certificate (from a file) or do I have to register it in the X509Store, and if so, which one?
Regards.

**Comment by hgupta9** [comment]
I've opened a new issue for the SFTP question.
