### ISSUE TITLE
[Feature] Provide overloaded Upload() method that takes a Stream...

### ISSUE THREAD

**Issue by natiki** [hgupta9/FluentFTP#32]
Hi,

In my use case I already have a Stream and want to write it to upload it.  Having to save it locally first before calling UploadFile() is a bit cumbersome.

**Comment by hgupta9** [comment]
Done.
Download the latest https://www.nuget.org/packages/FluentFTP/16.0.18 to use UploadFile() with streams or bytearrays.

**Comment by natiki** [comment]
Hi Harsh,

Much appreciated and the quick turn around. Works perfectly.

**Comment by hgupta9** [comment]
Thank you. Glad to help.
