### ISSUE TITLE
Method UploadFiles is throwing Expcetion "bad login"

### ISSUE THREAD

**Issue by thehekycz** [hgupta9/FluentFTP#33]
Hi,
i think i found an issue. When i connect to FTP server via Total Commander, then when i connect to FTP via your FtpClient class at the same time, then when i use method UploadFile on instance of FtpClient then method is throwing Exception with InnerException "bad login". This behavior stops when i disconnect from FTP in Total Commander.

**Comment by hgupta9** [comment]
Maybe your server only allows one connection at a time?

**Comment by thehekycz** [comment]
I dont think that't it. Because when i am uploading maybe 5 files then 4 files are loaded and in the fifth it throws excpetion.

**Comment by hgupta9** [comment]
Unless you can provide more details its impossible to debug. Can you show same code that you are using or the approx usage of the library? Is your problem similar to https://github.com/hgupta9/FluentFTP/issues/34 where the server disconnects because there are too many connections?

**Comment by hgupta9** [comment]
I've fixed this issue in the latest version which you can grab from nuget. Does it work for you now?

**Comment by thehekycz** [comment]
I am sorry, i could not answer earlier. Yes, it work for me. Thank you very much!
