### ISSUE TITLE
GetListing doesn't return the current directory and the parent directory (. and ..)

### ISSUE THREAD

**Issue by m4rs2k** [hgupta9/FluentFTP#41]
Hi, 

GetListing() and GetListing("", FtpListOption.AllFiles) don't return the current directory and the parent directory.

However, the LIST COMMAND returns those 2 files.

TELNET 127.0.0.1 21
-----------------------------
220 Hello, I'm freeFTPd 1.0
USER test
331 Password required for test
PASS Bonjour123
230 User test logged in
PASV
227 Entering passive mode (127,0,0,1,226,7)
LIST
150 Opening ASCII mode data connection
226 Directory send OK

TELNET 127.0.0.1 57863
-----------------------------
drwxr-xr-x   1 root       root            0 Jan 30 12:17 .
drwxr-xr-x   1 root       root            0 Jan 30 12:17 ..
-rw-r--r--   1 root       root            8 Jan 30 12:17 Bonjour.txt
drwxr-xr-x   1 root       root            0 Dec 22  2016 final_gabarit2015B
drwxr-xr-x   1 root       root            0 Dec 22  2016 tmp2

**Comment by hgupta9** [comment]
Can you try with `GetListing("/")`

**Comment by m4rs2k** [comment]
same result. I tried
- GetListing("")
- GetListing(".")
- GetListing("/")
- GetListing("./")
- GetListing("/./")

![image](https://cloud.githubusercontent.com/assets/25437282/22508063/4b0b6f36-e856-11e6-8c7b-d14dd2875fd1.png)

The behavior also occurs with subfolders

![image](https://cloud.githubusercontent.com/assets/25437282/22508252/294a6202-e857-11e6-95da-f94389e2070d.png)

**Comment by m4rs2k** [comment]
The "problem" is here.

![image](https://cloud.githubusercontent.com/assets/25437282/22509031/58a1704c-e85a-11e6-9d47-f755dbc91109.png)

Do you plan to support it in a future release?

**Comment by hgupta9** [comment]
Ok so if you are at the root directory, you _cannot_ go one level up. The FTP spec does not allow for that. However if your working directory is NOT at the root level, then a path beginning with `.` can be supported.

**Comment by m4rs2k** [comment]
I know that I cannot go one level up if I'm at the root directory.  But many(all?) FTP servers return these 2 items. So I expect to see them in the object representation. I mean, I would prefer an non altered result.

*Also, my Sftp client returns these items. I want to avoid different behaviors.

**Comment by hgupta9** [comment]
Which 2 items? So far you've only talked about going one level up / listing parent folders so I have no idea which 2 items you mean.

**Comment by m4rs2k** [comment]
![image](https://cloud.githubusercontent.com/assets/25437282/22512776/1182c8b0-e868-11e6-8e58-9d96e7557e94.png)

**Comment by hgupta9** [comment]
Oh I thought you wanted something else entirely. I thought you wanted to be able to _list_ the parent directory, meaning when you pass `GetListing("../")` it should return the parent directory's files. If you simply want to add the items into the result, I can add an option for it. Wait a sec.

**Comment by hgupta9** [comment]
Added `FtpListOption.IncludeSelfAndParent` in the latest version. Does it work for ya?

https://www.nuget.org/packages/FluentFTP/16.2.1

**Comment by m4rs2k** [comment]
Thx :)
