### ISSUE TITLE
DownloadFile with restart option?

### ISSUE THREAD

**Issue by aamirMasood** [hgupta9/FluentFTP#42]
Hi there,

The `OpenRead` method is now obsolete and `DownloadFile` is recommended instead. But what about `OpenRead(string path, FtpDataType type, long restart)`? There is no way to use `DownloadFile`  with restart option. The workaround is to use the static `OpenRead` method but that is only a workaround. Any other options / plans?

**Comment by hgupta9** [comment]
Thank you for this info. DownloadFile is a new API and to get info about such advanced use cases I have left OpenRead still in there. It will be supported until all use cases are tackled. For now you can still use OpenRead. I will improve DownloadFile with resuming support and get back when its ready.

**Comment by hgupta9** [comment]
As of now its better to use OpenRead() for this advanced use case.
