### ISSUE TITLE
Cannot install FluentFTP into a PCL project

### ISSUE THREAD

**Issue by flyingxu** [hgupta9/FluentFTP#45]
Hi,

I'm trying to use FluentFTP in my PCL project with .net 4.5 and profile 111.

I got this error:

> PM> Install-Package FluentFTP
Attempting to gather dependency information for package 'FluentFTP.16.2.1' 
with respect to project 'ABCD', targeting '.NETPortable,Version=v4.5
,Profile=Profile111'
Attempting to resolve dependencies for package 'FluentFTP.16.2.1' with 
DependencyBehavior 'Lowest'
Resolving actions to install package 'FluentFTP.16.2.1'
Resolved actions to install package 'FluentFTP.16.2.1'
  GET https://api.nuget.org/packages/fluentftp.16.2.1.nupkg
  OK https://api.nuget.org/packages/fluentftp.16.2.1.nupkg 145ms
Installing FluentFTP 16.2.1.
Adding package 'FluentFTP.16.2.1' to folder 'D:\abcd\packages'
Added package 'FluentFTP.16.2.1' to folder 'D:\abcd\packages'
Install failed. Rolling back...
Package 'FluentFTP.16.2.1' does not exist in project 'ABCD'
Removing package 'FluentFTP.16.2.1' from folder 'D:\abcd\packages'
Removed package 'FluentFTP.16.2.1' from folder 'D:\abcd\packages'
Install-Package : Failed to add reference to 'System.Web'. Please make sure 
that it is in the Global Assembly Cache.
At line:1 char:1
>+ Install-Package FluentFTP
>+ ~~~~~~~~~~~~~~~~~~~~~~~~~
>    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
>    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.
>PackageManagement.PowerShellCmdlets.InstallPackageCommand

The reason it failed to add reference to 'System.Web' is because System.Web cannot be added into a PCL project.

I'm not sure if this is an issue or not, do we have a workaround?

**Comment by hgupta9** [comment]
Actually I tried building for PCL but [PCL does not contain the Socket class](http://stackoverflow.com/questions/35196097/is-there-any-way-to-create-a-socket-in-portable-class-library). Maybe if we can use [this library](https://github.com/rdavisau/sockets-for-pcl) we can target the PCL framework.

**Comment by hgupta9** [comment]
I've finally got VS 2015 community installed and I'm investigating a PCL version. Stay tuned! Shoutback if you want to help!

**Comment by hgupta9** [comment]
Due to lacking Socket support in PCL, we cannot release FluentFTP on PCL.
