### ISSUE TITLE
Error while downloading the file from the server. See InnerException for more info

### ISSUE THREAD

**Issue by thedeveloper2** [hgupta9/FluentFTP#453]
**FTP OS:**  Windows 
It could see this issue more frequently. I am using latest version of FluentFTP.
 
**FTP Server:** 

Exception 1: Timed out trying to read data from the socket stream!
FluentFTP.FtpException: Error while downloading the file from the server. See InnerException for more info. ---> System.TimeoutException: Timed out trying to read data from the socket stream!     at FluentFTP.FtpSocketStream.Read(Byte[] buffer, Int32 offset, Int32 count)     at FluentFTP.FtpSocketStream.ReadLine(Encoding encoding)     at FluentFTP.FtpClient.GetReply()     at FluentFTP.FtpClient.DownloadFileInternal(String remotePath, Stream outStream, Int64 restartPosition, IProgress`1 progress)     --- End of inner exception stack trace ---     at   --- End of stack trace from previous location where exception was thrown ---     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)     at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()

Exception 2: Failed to get the EPSV port from: Transfer complete.   

FluentFTP.FtpException: Error while downloading the file from the server. See InnerException for more info. ---> FluentFTP.FtpException: Failed to get the EPSV port from: Transfer complete.     at FluentFTP.FtpClient.OpenPassiveDataStream(FtpDataConnectionType type, String command, Int64 restart)     at FluentFTP.FtpClient.OpenDataStream(String command, Int64 restart)     at FluentFTP.FtpClient.OpenRead(String path, FtpDataType type, Int64 restart, Boolean checkIfFileExists)     at FluentFTP.FtpClient.DownloadFileInternal(String remotePath, Stream outStream, Int64 restartPosition, IProgress`1 progress)     --- End of inner exception stack trace ---     at  --- End of stack trace from previous location where exception was thrown ---     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)     at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()

**Comment by knunn-kygunco** [comment]
I mean if you're going to close it at least point future people to the right issue.
