### ISSUE TITLE
How to use certificates for FTPS connections in C# .?

### ISSUE THREAD

**Issue by ajpprivate** [hgupta9/FluentFTP#47]
Hi HGupta,

I am using your library for making connections with FTP sites. now i am facing some problems with FTPS sites(Sites with SSL enabled). I have set my FTPS site with IIS and i am using the code in below.

````
FtpClient conn = new FtpClient();
conn.Host = firewallSslDetails.Address;
conn.Credentials = new NetworkCredential(firewallSslDetails.UserName, firewallSslDetails.Password);
conn.SslProtocols = System.Security.Authentication.SslProtocols.Default;

X509Certificate2 cert = new X509Certificate2(@"C:\Users\BizTalk360\Desktop\FtpSites\ServerCert.cer");
 conn.EncryptionMode = FtpEncryptionMode.Explicit;
 conn.DataConnectionType = FtpDataConnectionType.AutoActive;
 conn.DataConnectionEncryption = true;
 conn.EnableThreadSafeDataConnections = false;
 conn.ClientCertificates.Add(cert);
 conn.ValidateCertificate += new FtpSslValidation(OnValidateCertificate);
 
 conn.Connect();
 conn.ConnectTimeout = 60000;
 Console.WriteLine("Connection Established");
 if (conn.DirectoryExists("/" + firewallSslDetails.Folder))
 {
     Console.WriteLine("Directory Exists..!");
     conn.SetWorkingDirectory("/" + firewallSslDetails.Folder);
     FtpListItem[] items = conn.GetListing();
     Console.WriteLine(items.Length);
 }
 else
 {
     Console.WriteLine("Directory does not exist");
 }
````

I am new to programming and i can't figure out how to verify and connect to the server.

Thanks.

**Comment by hgupta9** [comment]
Please add your code back into the question. Surround the code with four backticks at the start and end to mark it as a code block... like this:

<pre>
````
code
````
</pre>

**Comment by ajpprivate** [comment]
Updated the question. Please take a look.

**Comment by hgupta9** [comment]
What error are you facing? Can you send a screen shot or error message. Also if you are connecting with client certificates you will need to provide the CER file so we can debug on our end.

**Comment by ajpprivate** [comment]
At this time i've found that my local machine's FTP is broken. I'll test the code with some other FTP server and i'll reconfirm it.

**Comment by hgupta9** [comment]
I'm closing this issue since you did not provide enough information. If you have this problem in the future, add a message here and I'll reopen it. Regards.
