### ISSUE TITLE
Concurrency issue in FtpClient

### ISSUE THREAD

**Issue by lucamit** [hgupta9/FluentFTP#48]
In FTP Client we  are not initializing  m_lock as static.
I wanted to  append  file using multiple thread. but since m_lock object is per FtpClient different connection are  failing  on concurrency. 
Getting below exception:
"The process cannot access the file because it is being used by another process."
I tested by making m_lock object as static , and that seems to work.

**Comment by hgupta9** [comment]
I think this was a design decision by Trosclair (original author). Where are you getting the exception? As per my understanding, multiple threads with multiple FluentFTP clients should work just fine. If we make it static then only one thread is allowed to progress at a time. This will cause delays for people who need multiple FTP connections at once.

**Comment by lucamit** [comment]
In case of multiple thread with multiple fluent ftpclient,If client C1 is appending file F1 and client C2  also wants to append File F1.Then this use case will give the exception.
