### ISSUE TITLE
.NET Core

### ISSUE THREAD

**Issue by imperugo** [hgupta9/FluentFTP#5]
Are you planning to support .NET Core?

**Comment by hgupta9** [comment]
Do you need it for a project or are you just curious? If its simple enough I can configure a build.

**Comment by imperugo** [comment]
Real project of course

**Comment by jiabiao** [comment]
Our many projects use System.Net.FtpClient , We are planing to port them to .net core. 
That would be great if FluentFTP support .net core.

**Comment by hamu01** [comment]
@hgupta9 I create a new feature to support .net core, The feature do very little changes, the main purpose is to support .net core, but there is a bug when upload file, sometimes it only upload partial document, I don't know why. 
I don't have the push permission. How can I contribute my code?

**Comment by hgupta9** [comment]
Create a Pull Request, or PR.

1. Click **Fork** on the top right
2. Open your version here : https://github.com/Zoltan666/FluentFTP
3. Download [Github Desktop](https://desktop.github.com/) and login to your account
4. Click **+** (top left) then **Clone** and select FluentFTP and click Clone/OK
5. Select a folder on your PC to place the files
6. Edit the files using any editor
7. Click **FluentFTP** on the list (left pane) in Github Desktop
8. Click **Changes** (top)
9. Type a Summary, and click **Commit** (bottom)
10. Click **Sync** (top right)
11. Then create a PR by going [here](https://github.com/hgupta9/FluentFTP/pulls).
12. Click **compare across forks**, and select your version on the right ("head fork").
13. Press OK and type some text about what changes you made

**Comment by hamu01** [comment]
OK, got it, I'll create a pull request later.

**Comment by hamu01** [comment]
I already create a pull request, the address is #21

**Comment by hgupta9** [comment]
@hamu01 - Any updates on this? Or should I try to create a merged repo myself?

**Comment by hgupta9** [comment]
I've started working on this since hamu is taking forever. Except it this week!

**Comment by hgupta9** [comment]
@imperugo @jiabiao @hamu01 
I don't currently have VS 2015 / VS 2017 installed. **Does anyone have a suitable VS version for .NET core and is willing to test the .NET core version?** I have made most of the code .NET core compatible following the example of @hamu01's code, so you should have minimal compile issues. Anyone willing can simply take the latest trunk and add a project build configuration for .NET core with the "CORE" compiler variable.

**Comment by hgupta9** [comment]
I've finally got VS 2015 community installed. I'm working on a .NET Core version. Stay tuned!

**Comment by jiabiao** [comment]
@hgupta9  Great ! I'm looking forward to it.

**Comment by hgupta9** [comment]
Its mostly done, however FTPS will not be available since `SslStream` is not included in the .NET Core 1.0. We will need to wait for 6 months for .NET Core 2.0 for that to happen.

**Comment by jiabiao** [comment]
@hgupta9 
It's enough for me, as I just use normal ftp.

BTW , There is a predefined conditional compilation symbol for every framework:
```csharp
#if NETSTANDARD1_6
     //code for net strandard 1.6
#elif NETSTANDARD2_0
    //code for net strandard 2.0
#elif NET45
     //code for net45
#endif
```
https://docs.microsoft.com/en-us/dotnet/articles/core/tutorials/libraries#how-to-multitarget

**Comment by hgupta9** [comment]
Until this [issue ](http://stackoverflow.com/questions/42454085/publishing-a-net-core-project-to-nuget-which-framework-version-to-use)is resolved I cannot publish for nuget. Do you have any ideas?

**Comment by hgupta9** [comment]
@imperugo @jiabiao @hamu01

The first .NET core version of FluentFTP is published on nuget! https://www.nuget.org/packages/FluentFTP/16.2.4

Please check it out and report any issues you find!
