### ISSUE TITLE
Async Put

### ISSUE THREAD

**Issue by greenbergjosh** [hgupta9/FluentFTP#50]
I would think there would be an obvious way to:

FtpClient c = new FtpClient()
...
await c.UploadFile(localfile, remotefile);

I don't see how to do this. I tried BeginOpenWrite and attempted to use Task..FromAsync but could not get it working. Can you please provide an example. 

Thank you.

**Comment by hgupta9** [comment]
Does the await keyword work with OpenRead or OpenWrite? If it does then I will add similar methods (BeginUploadFile) for UploadFile and friends.

**Comment by jblacker** [comment]
@hgupta9  This is implemented in my current pull request.

**Comment by hgupta9** [comment]
@greenbergjosh Can you try using async/await in the current version? https://www.nuget.org/packages/FluentFTP/16.5.0

Example

> #if (CORE || NETFX45)

**Comment by hgupta9** [comment]
Since support for `async`/`await` has been added in FluentFTP 16.5 and onwards I'm closing this issue. Feel free to reply here if you encounter any problems, or add a new issue if its unrelated.
