### ISSUE TITLE
Append to file

### ISSUE THREAD

**Issue by ajaywazir** [hgupta9/FluentFTP#52]
Hi 
Do you have any example to show how to append text to existing text file.
Regards
Ajay

**Comment by hgupta9** [comment]
Something like this. I've not tested it so you may have to correct some small errors.

       using (FtpClient conn = new FtpClient()) {
                conn.Host = "localhost";
                conn.Credentials = new NetworkCredential("ftptest", "ftptest");
                
                using (Stream ostream = conn.OpenAppend("/full/or/relative/path/to/file")) {
                    try {
                        ostream.Position = ostream.Length;
                        var sr = new StreamWriter(ostream);
                        sr.WriteLine(...);
                    }
                    finally {
                        ostream.Close();
                    }
                }
       }

**Comment by hgupta9** [comment]
You can also append to a file using the new UploadFile() API:

- UploadFile(.... FtpExists.Append)
