### ISSUE TITLE
Multiple upload error

### ISSUE THREAD

**Issue by maxMakaronok** [hgupta9/FluentFTP#54]
Unusual problem,when i upload many files in one thread. Sometimes i have error in uploading  (example Failed to get the EPSV port from: 6351, or unknown command)

but i try it again it work fine

i have a bad issue now, - if error thread.sleep(10 seconds)
````
 ftpClient = new FtpClient
            {
                Host = ftpClientSettings.Host,
                Credentials = new NetworkCredential(ftpClientSettings.Login, ftpClientSettings.Password),
                EnableThreadSafeDataConnections = false,
               
            };
````
i use the win service, that each 2 hours upload files to different servers

**Comment by hgupta9** [comment]
Sorry I cannot understand your post. Unless you clarify/explain it better its impossible to solve.
