### ISSUE TITLE
Upload of great number of files (100+) suddenly slow

### ISSUE THREAD

**Issue by alex-mazzariol** [hgupta9/FluentFTP#56]
Hi,
since update to last nuget 16.2.4 my batch uploads (1000 - 2000 files per directory, 5-6 such uploads) became very slow via FtpClient.UploadFile() method.

I've been able to trace the problem to the now-always-executed FileExists() method call, which is present at the beginning of every UploadFile() overload and that should fix issue #46. Since commit c484877a134f9ff10bbaed6725f41c4016af9f87 the FileExists() method is called before every single upload, and if the file exists it is deleted before the actual upload.

While this may be a nice workaround for the issue of uploading a file smaller than the previous, it becomes a nightmare for batch transfers: the directory is checked every time, and every successful upload produces a longer directory listing, so the check gets slower and slower! The transfer time skyrockets from seconds to hours.

I've been able to temporarily work around the problem by directly invoking the UploadFileInternal method via reflection (I was already using streams, so it's been easy), but I'm submitting this issue for a more structured and robust solution.

It could either be a way to completely ignore file existence checks (so people knowing that could just turn this check off) or a bulk transfer for a specific destination directory. In this second case the file list is checked only once, before the transfer begins, and this behavior becomes the distinguishing feature from a loop of UpdateFile() calls.

**Comment by hgupta9** [comment]
Thank you for this detailed and helpful report. I'll try to implement both of the methods you recommended.

**Comment by hgupta9** [comment]
Both methods implemented in [16.2.5](https://www.nuget.org/packages/FluentFTP/16.2.5). Can you download and see if that works for you?

- `UploadFile()` now has `checkFileExistance` arg
- New `UploadFiles()`
- New `DownloadFiles()`

**Comment by alex-mazzariol** [comment]
I tested the new parameter and it does indeed work, back to full speed (3 threads concurrently uploading with the same control connection).

Thank you!

P.S. I think you can update the project "Add High-Level API" moving the ToDo items relative to the multiple files into the "Done" box 😄

**Comment by hgupta9** [comment]
Sure, no problem. Glad everything worked well :)
