### ISSUE TITLE
Unneeded calls to GetWorkingDirectory() in GetListing(path, options)

### ISSUE THREAD

**Issue by Charles113** [hgupta9/FluentFTP#58]
Hi, 

i just did some profiling because my app was a little bit slower than FileZilla when traversing all directories.
My app has many Calls to GetListing and i noticed GetWorkingDirectory() is called even when not needed.
My profiler said GetWorkingDirectory() uses up 12% of my total execution time.

So i changed the GetListing Function to only call GetWorkingDirectory() when needed

```
FtpListItem item = null;
List<FtpListItem> lst = new List<FtpListItem>();
List<string> rawlisting = new List<string>();
string listcmd = null;
string pwd = null;
string buf = null;
bool includeSelf = (options & FtpListOption.IncludeSelfAndParent) == FtpListOption.IncludeSelfAndParent;

if (path == null || path.Trim().Length == 0) {
	pwd = GetWorkingDirectory();
	if (pwd != null && pwd.Trim().Length > 0)
		path = pwd;
	else
		path = "./";
} else if (!path.StartsWith("/")) {
	pwd = GetWorkingDirectory();
	if (pwd != null && pwd.Trim().Length > 0)
	{
		if (path.StartsWith("./"))
			path = path.Remove(0, 2);
		path = string.Format("{0}/{1}", pwd, path).GetFtpPath();
	}
}
```

Maybe this is helpful to someone

Cheers

**Comment by hgupta9** [comment]
Thank you for this! I will try to absorb your code into the trunk.

**Comment by hgupta9** [comment]
Your code has been absorbed into the trunk and will be available in the next release!
