### ISSUE TITLE
Changing the rights to the downloaded file

### ISSUE THREAD

**Issue by slagusev** [hgupta9/FluentFTP#59]
Hello!
How can I set the permissions 777 on the uploaded FTP server file?

**Comment by hgupta9** [comment]
Sorry, there is no in-built API for these. I'll add them shortly, but if you need it right now please use:

          if (!(reply = conn.Execute("SITE CHMOD 640 yourfilename.txt")).Success) {
                 throw new FtpCommandException(reply);
          }

**Comment by hgupta9** [comment]
Thanks to your idea, I have implemented the following new API. Check it out and let me know!
- Chmod()
- GetChmod()
- SetFilePermissions()
- GetFilePermissions()

**Comment by hgupta9** [comment]
You can now just do:

    client.Chmod("\path\to\file.txt", 777)

**Comment by hgupta9** [comment]
You must download the latest from nuget to use it. https://www.nuget.org/packages/FluentFTP/
