### ISSUE TITLE
What exactly EnableThreadSafeDataConnections does?

### ISSUE THREAD

**Issue by nvivo** [hgupta9/FluentFTP#64]
I'm trying to concurrently upload files using a pool of tasks and a concurrent queue. Each task has an FTP client that grabs the next file in the queue and uploads it. With `EnableThreadSafeDataConnections`.  it seems only one file is uploaded at a time even though I'm using multiple clients. I have also tried with a single client, but had similar results. The docs say that `EnableThreadSafeDataConnections` will start a new connection for each file, but that doesn't seem to happen.

Can you please clarify what happens when we set EnableThreadSafeDataConnections is true or false? "Thread safe" is a very vague term.

**Comment by hgupta9** [comment]
EnableThreadSafeDataConnections is an older feature built by the original author. If true, it opens a new FTP client instance (and reconnects to the server) every time you try to upload/download a file. It used to be the default setting, but it affects performance terribly so I disabled it and found many issues were solved as well as performance was restored. I believe if devs want multi-threaded uploading they should just start a new BackgroundWorker and create/use FtpClient within that thread. Try that if you want concurrent uploading, it should work fine.
