### ISSUE TITLE
Strong name for .nuget version

### ISSUE THREAD

**Issue by cyberangel** [hgupta9/FluentFTP#66]
Hello, for my project I need the assembly to have a strong name.
This limits the possible use of the great .nuget implementation.

Could you add a certificate and sign it?

Thanks,
Honza

**Comment by hgupta9** [comment]
Its possible. Any guides to help with this?

Same as #10

**Comment by hgupta9** [comment]
Done as of https://github.com/hgupta9/FluentFTP/pull/73. Will be uploaded in next nuget version.

**Comment by ernie1000** [comment]
When will the next nuget version be released?

**Comment by hgupta9** [comment]
I can release it today.

**Comment by hgupta9** [comment]
Fixed in 16.4.1.

**Comment by hgupta9** [comment]
You can get it from here https://www.nuget.org/packages/FluentFTP/16.4.1

**Comment by ernie1000** [comment]
Thank you very much for the fast response!
