### ISSUE TITLE
Delete Directory recursively throws exception

### ISSUE THREAD

**Issue by gibuz1991** [hgupta9/FluentFTP#67]
Hello,
I'm trying to delete a not empty folder on my server. Here the code:

**_client.DeleteDirectory(path,true,false);**

I got the following exception:

**Directory not empty**

Is that an issue or just my code mistake?

Thanks,
Marco

**Comment by hgupta9** [comment]
It seems to be an issue. I'll check it out.

**Comment by hgupta9** [comment]
Also try with "allfiles" param which forces deletion of hidden files.

    _client.DeleteDirectory(path, true, FtpListOption.AllFiles, false);

**Comment by hgupta9** [comment]
If you are still having the problem then please reply and I'll reopen this issue.

**Comment by pbindy** [comment]
I have the same issue with this code.
(folder is not empty)
`   FtpClient.DeleteDirectory(folderPath, true, FtpListOption.AllFiles, false);`
this error says "File is busy"
but somehow this line works
` FtpClient.DeleteDirectory(folderPath, true, true);`

**Comment by hgupta9** [comment]
@pbindy Thanks for the report. The line that works uses `fastMode = true`. I'll switch to `fastMode` as default from now on.

**Comment by pbindy** [comment]
I come back because I'm experiencing another issue with the DeleteDirectory method.

I upload some folders and files in the beginning of my process and around 10mn later, I delete a folder which contains files
I use
`FtpClient.DeleteDirectory(folderPath, true, true);`

but I sometimes get the error:

> Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.

I don't know if the fact that I let around 10mn the FtpConnection without doing anything with it is related. I always check if the FTPClient is connected, if not I reconnect.

Thank you for your help...

**Comment by The-Abc** [comment]
Same problem:

I am using 
conn.DeleteDirectory(dirToDelete, FtpListOption.AllFiles);
conn.DeleteDirectory(dirToDelete);

Exception:
FtpCommandException: No files found or invalid directory or permission problem.

I have uploaded the directory before. It definitely exists (checking it in code).

Using a Bachmann PLC Ftp Server.

**Comment by The-Abc** [comment]
When I use DeleteFile on an empty directory, the directory will be deleted. 

As a workaround I have built my own DelteDirectory Function which is recursive and a uses DeleteFile.

**Comment by nickpie** [comment]
Hello?I tried FtpClient.DeleteDirectory(path,FtpListOption.AllFiles) and got a mistake "Directory not empty"
How can I delete a directory which is not empty?
