### ISSUE TITLE
UploadFiles() => Can't Find File

### ISSUE THREAD

**Issue by bernardocout** [hgupta9/FluentFTP#70]
Hi! 
I'm having an issue with UploadFiles method.
This is my code:

```
var count = _client.UploadFiles(filesPaths, remotePath, true, true);
foreach(var path in filesPaths)
{
    AddLog(string.Format("Uploaded File: {0}", path));
}
```
And after execute UploadFiles it throws an exception saying "Can't find file". I discovered when I use remotePath = "/Uploads" I have this issue, but when I set remotePath to "/", the method uploads files without problems. I checked user permissions and he can do everything.
I don't know what could be the problem. I read the source code and I didn't find anything weird.
Is it a bug of FluentFTP? Or am I missing something?
Thanks in advance!

**Comment by hgupta9** [comment]
As per the docs `Remote directories are NOT created if they do not exist.` 

Can you ensure that the "/uUploads" folder exists on the server using `CreateDirectory`??

**Comment by bernardocout** [comment]
Sorry, it was "/Uploads". I didn't check using CreateDirectory but it's a local ftp which I'm using for testing and yes, the folder "/Uploads" exists. I'm using your library from a webapi, it works very well when I download files but I'm having this issue to upload files.

**Comment by bernardocout** [comment]
I let you the exception stack trace in order to explain better my problem. The ex message is "Can't find file". I have tried with CreateDirectory without any positive result, it continues throwing the same error.

   ```
en FluentFTP.FtpClient.OpenPassiveDataStream(FtpDataConnectionType type, String command, Int64 restart)
   en FluentFTP.FtpClient.OpenDataStream(String command, Int64 restart)
   en FluentFTP.FtpClient.GetNameListing(String path)
   en FluentFTP.FtpClient.UploadFiles(String[] localPaths, String remoteDir, Boolean overwrite, Boolean createRemoteDir)
   en Amerisource.Service.Managers.FtpManager.UploadFiles(String[] filesPaths, String remotePath) en D:\devlights\Mike\Amerisource\Src\Amerisource.Service\Managers\FtpManager.cs:línea 140
   en Amerisource.Service.EdiConnectService.UploadFiles(String[] filesPaths) en D:\devlights\Mike\Amerisource\Src\Amerisource.Service\EdiConnectService.cs:línea 43
   en Amerisource.Web.Controllers.Api.EdiNetworkConnectController.<PostSendEdi>d__5.MoveNext() en D:\devlights\Mike\Amerisource\Src\Amerisource.Web\Controllers.Api\EdiNetworkConnectController.cs:línea 101
```

**Comment by hgupta9** [comment]
I think the CHMOD settings of the "Uploads" folder is wrong. Can you change it using the [SetFilePermissions/Chmod](https://github.com/hgupta9/FluentFTP#file-permissions) functions? See the docs for more info.

**Comment by bernardocout** [comment]
I changed my ftp server and it works now! I think it was something about permissions, but I tested with SetFilePermissions and it didn't work either.

**Comment by hgupta9** [comment]
Great!
