### ISSUE TITLE
VS2010 nuget install FluentFTP 16.4.0 error

### ISSUE THREAD

**Issue by yuanrui** [hgupta9/FluentFTP#72]
![install-fluentftp-error](https://cloud.githubusercontent.com/assets/3859838/25030167/d2481ee0-20f5-11e7-9309-0ef9e706a2dc.png)

In Vs 2010 use nuget (2.8.6) install FluentFTP 16.4.0 error 
the error message:
'System.Runtime' already has a dependency defined for 'FluentFTP'.

But Install-Package FluentFTP -Version 16.3.0 success

**Comment by hgupta9** [comment]
What is your project type? .NET? .NET Core? Which framework version? Can you tell me exactly so I can create that project type here and check on my VS.

**Comment by hgupta9** [comment]
I installed in VS 2012 for .NET 2 project + VS 2017 for .NET 4.5, .NET Core, etc. All are working.

However in VS 2012 I had to update the Nuget plugin. Can you try updating your nuget plugin in VS 2010 and try again?

**Comment by yuanrui** [comment]
My project type is class lib, framework version is .net 4.0.
In my Vs 2010, my nuget current version is 2.8.6, I try to set nuget plugin update, but not work.

I try to create a empty console project, and try to use nuget cmd install
Install-Package FluentFTP
![install-fluentftp-error2](https://cloud.githubusercontent.com/assets/3859838/25116095/2e4d1408-243d-11e7-920f-3a08302d4b44.png)
but is report error too.

So, I download https://dist.nuget.org/win-x86-commandline/latest/nuget.exe, and in cmd.exe use nuget.exe install FluentFTP, and success!
![install-fluentftp-success](https://cloud.githubusercontent.com/assets/3859838/25116189/bf0fb7c0-243d-11e7-8e8e-7919980bf69f.png)

Any way, thanks!

**Comment by hgupta9** [comment]
Thats great!!

**Comment by JintomonSunny** [comment]
Hi Hg 
I am facing the same problem what yuanrui has faced 
I have tried the solution what he has explained still its not working . 

VS2010
Windows Application 
.Net Framework 4

But in my VS2017 community its getting installed successfully
how can i resolve the same in VS2010

**Comment by hgupta9** [comment]
You need to update your "nuget.exe" inside VS 2010.

**Comment by JintomonSunny** [comment]
Thank you  HG. 

I have updated the "nuget.exe" inside VS 2010. and still it was not working 
then i copied and pasted the "fluentFTP.dll" from VS2017 project to VS2010  project 
It Started working 

Thank you once again.

**Comment by hgupta9** [comment]
I solved this in the latest nuget 17.2.0 by deleting the `<group targetFramework=".NETStandard1.4">` and thereby dropping .NET standard 1.4 support since anyways we need 1.6 for the `SslStream`.

https://www.nuget.org/packages/FluentFTP/17.2.0
