### ISSUE TITLE
FTPS Passive Explicit closing stream err 426

### ISSUE THREAD

**Issue by SteveB360** [hgupta9/FluentFTP#763]
**FTP OS:** Unisys OS 2200 Mainframe

**FTP Server:** Proprietary

**Computer OS:** ? Win 10

**FluentFTP Version:** ? 35.0.5

I'm using FTPS Passive Explicit to connect to the Unisys mainframe. FluentFTP download PASV Explicit on port 21 works. Upload PASV on port 21 doesn't work, Explicit doesn't seem to matter.

                ftpsclient = new FtpClient(host, port, userID, pass);
                ftpsclient.EncryptionMode = FtpEncryptionMode.Explicit;
                ftpsclient.DataConnectionType = FtpDataConnectionType.PASV;
                ftpsclient.ValidateAnyCertificate = true;
                ftpsclient.Connect();
                ftpsclient.Execute("ACCT SPSE");
. . . 
                ftpsclient.UploadDataType = FtpDataType.ASCII;
                xferResult = ftpsclient.UploadFile(local, host, FtpRemoteExists.NoCheck, false, FtpVerify.None);

The xferResult is a fail. So I stepped through the execution. It looks like several buffers are written successfully. Then after the file has been sent, it gets to a chunk of code in FtpClient_FileUpload.UploadFileInternal() around line 895 (below) and gets a reply with an error code 426, that the stream has been closed.

                               upStream.Dispose();

				// FIX : if this is not added, there appears to be "stale data" on the socket
				// listen for a success/failure reply
				try {
					while (!m_threadSafeDataChannels) {
						var status = GetReply();

						// Fix #387: exhaust any NOOP responses (not guaranteed during file transfers)
						if (anyNoop && status.Message != null && status.Message.Contains("NOOP")) {
							continue;
						}

						// Fix #353: if server sends 550 or 5xx the transfer was received but could not be confirmed by the server
						// Fix #509: if server sends 450 or 4xx the transfer was aborted or failed midway
						if (status.Code != null && !status.Success) {
							return FtpStatus.Failed;

From the mainframe log (attached Mainframe Log 2021-10-08.docx) it appears the client closed the stream. 

If I comment out the upStream.Dispose() immediately above on line 894 I stop getting the 426 code from the mainframe. But then I found I am getting an unhandled System.IO.IOException with an Inner exception
{"Unable to read data from the transport connection: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.."}

**Logs :**
```
# Connect()
Status:   Connecting to ***:21
Response: 220 DIS    Unisys 2200 FTP Server( cpFTP Version 5R1-1A06  )ready.
Command:  AUTH TLS
Response: 234 AUTH command accepted. Start of security negotiation.
Status:   FTPS Authentication Successful
Status:   Time to activate encryption: 0h 0m 0s.  Total Seconds: 0.3754709.
Command:  USER ***
Response: 331 Password required for SS9006SB.
Command:  PASS ***
Response: 230 User SS9006SB logged in.
Command:  PBSZ 0
Response: 200 Protection buffer size set to zero.
Command:  PROT P
Response: 200 Protection level of data connection set to Private.
Command:  FEAT
Response: 211-Extensions supported
Response: AUTH TLS
Response: PBSZ
Response: PROT
Response: 211 End of features
Status:   Text encoding: System.Text.ASCIIEncoding+ASCIIEncodingSealed
Command:  SYST
Response: 215 Unisys 2200 system type ( exec 49R4 ).
Warning:  Cannot auto-detect listing parser for system 'Unknown', using Unix parser
Command:  ACCT SPSE
Response: 200 Current ACCT is "SPSE".

# UploadFile("c:\temp\st119.cob", "spse-sjb*source.st119/cob", NoCheck, False, None)

# OpenWrite("spse-sjb*source.st119/cob", ASCII)
Command:  TYPE A
Response: 200 Type set to A.

# OpenPassiveDataStream(PASV, "STOR spse-sjb*source.st119/cob", 0)
Command:  PASV
Response: 227 Entering Passive mode (129,220,190,75,4,6).
Status:   Connecting to ***:1030
Command:  STOR spse-sjb*source.st119/cob
Response: 150 Opening ASCII mode data connection for SPSE-SJB*SOURCE(1).ST119/COB 
Status:   FTPS Authentication Successful
Status:   Time to activate encryption: 0h 0m 0s.  Total Seconds: 0.1136639.
Status:   Disposing FtpSocketStream...
Response: 426 Data connection destroyed.
Status:   Failed to upload file.
Command:  QUIT
Response: 221 Goodbye.
Status:   Disposing FtpSocketStream...

# Dispose()
Status:   Disposing FtpClient object...
Status:   Disposing FtpSocketStream...
```

[Mainframe Log 2021-10-08.docx](https://github.com/robinrodricks/FluentFTP/files/7332724/Mainframe.Log.2021-10-08.docx)

**Comment by FanDjango** [comment]
Please follow the discussion on #996 concerning fixing the "Incorrect SSL shutdown" bug
