### ISSUE TITLE
Additional Logging Levels

### ISSUE THREAD

**Issue by jblacker** [hgupta9/FluentFTP#81]
Currently when you attach a `TraceListener` to `FtpTrace`, everything is issued at the DEBUG level.   Obviously, this is great for development and testing.  However, in production when an error occurs it would be nice to log the errors and ignore the tracing messages.  

I think the FtpTrace class would be greatly enhanced by simply adding levels so when a TraceListener is attached the logging can be filtered appropriately and errors can be handled by the appropriate people.  When using the low-level APIs this isn't a big deal, but this is especially important when a failure occurs using the high-level APIs.  For example, when using `UploadFile()` / `DownloadFile()`, there's no way to know what the failure if it returns false in production or in a release build.

Originally, I thought that maybe adding a "LastError" property to the `FtpClient` class would do the trick, but in a multi-threading environment this would be a nightmare.  What are your thoughts?

**Comment by hgupta9** [comment]
Dude, all of your ideas are great, but I would especially appreciate you help with a certain issue that I really can't fix. If you have time, could you check it out? Its really simple. Just open an FTP Client and create a folder with spaces (but on a FreeBSD Server, if you have one handy..) And then try using FluentFTP to GetListing() the stuff in that folder. It apparently doesn't work.

https://github.com/hgupta9/FluentFTP/issues/27

And yes, the tracing could be done. If you can list down specific places in the code that need CRITICAL or ERROR traces then I guess I could change those, so it can be logged properly in a production environment.

**Comment by jblacker** [comment]
I'd be happy to help implement some of these ideas, but wanted to post first since you're the library owner.  I'll spin up a FreeBSD VM sometime next week and take a look.  I was thinking the error traces could be added wherever the source is for a `a method returning false`.

**Comment by hgupta9** [comment]
Sure, help is always appreciated.
