### ISSUE TITLE
Short Circuit Multi-File Upload/Download

### ISSUE THREAD

**Issue by jblacker** [hgupta9/FluentFTP#83]
What do you think about having the option to make the `UploadFiles()` and `DownloadFiles()` "transactional"?

There are situations where you'd want to transfer an entire directory or set of files, and a partial failure is not acceptable.  Since these methods swallow up exceptions they will still continue to upload/download until it completes.  In the cases that this is not acceptable I propose that an options flag is added to change the behavior if needed:

1. None (current behavior)
2. Stop Uploading/Downloading and return false immediately (do not upload remaining files)
3. Throw when an exception is encountered
4. Delete the files (or created directories) that uploaded/downloaded successfully

The deletion option would be able to be combined with either option 2 or 3.  This functionality along with the logging enhancement I proposed in #81 would really help handling problems in a production environment.  Maybe a boolean flag can also be added to `UploadFile()`/`DownloadFile()` to cause the method to throw if an unresolvable error is encountered if requested.

**Comment by hgupta9** [comment]
Sure, they are all good ideas. It can be implemented. I'll try to do it soon. What do you think the API should look like?:

- A : `UploadFiles(<existing args>, int errorMode = 0, bool deleteFiles = false)`
- B : `UploadFiles(<existing args>, int flags)`

In option A, error mode is:
- 0 = Absorb error and reduce total file count
- 1 = Stop Uploading and return 0 immediately
- 2 = Throw when an exception is encountered

In option B, flags will be more complicated, maybe you can design it.

**Comment by jblacker** [comment]
I was thinking more along the lines of version B and I'd be happy to add it in.  It shouldn't be too difficult to add it in, and we can always throw for an invalid flag combination. :smiling_imp:

**Comment by hgupta9** [comment]
Okay, give it a shot. If you need something just ask.

**Comment by jblacker** [comment]
@hgupta9  I have this implemented, but I'm combining it with the implementation for #92 before I submit a PR.  Just a heads up...it's a bit ugly.  It works, but the signatures are getting big and the methods aren't as clean as they used to be.  It might (read:  _definitely_) need a refactor at some point in the near future.

**Comment by hgupta9** [comment]
Thanks. If they are too big we can switch to the object for config as you were saying. Or we could create class level properties for some.
