### ISSUE TITLE
Malformed PASV response: TYPE is now 8-bit binary

### ISSUE THREAD

**Issue by isvaljek** [hgupta9/FluentFTP#86]
I'm using NuGet 16.5.0 and when I try to connect with FTPS to Godaddy shared hosting, this is the exception I get:

> Malformed PASV response: TYPE is now 8-bit binary

this is my connection setup:

```
client.Host = deployment.ftp_details.host_name;
client.Port = deployment.ftp_details.port_number;
client.EncryptionMode = FtpEncryptionMode.Explicit;
client.SslProtocols = System.Security.Authentication.SslProtocols.Tls;
client.ValidateCertificate += new FtpSslValidation(cl_ValidateCertificate);
client.Credentials = new NetworkCredential(deployment.ftp_details.user_name, deployment.ftp_details.password);
client.DataConnectionType = FtpDataConnectionType.PASV; 
```

And this happens when I do a recursive directory UploadFiles.

Also, it seems that WinSCP connects correctly, but one thing to mention is that Godaddy sets the ftps port to 21 like the regular ftp. I have fully disabled Windows Firewall.

update: this seems to happen on one other host, not related to Godaddy.

**Comment by hgupta9** [comment]
Why are you using passive? Does active not work for you?

**Comment by isvaljek** [comment]
I'm trying to setup server to server ftp connection. So I'm still not sure which route is the best.
If I enable active mode, I'll have to open a lot of ports right?

**Comment by hgupta9** [comment]
Remove this line for automatic detection:
> client.DataConnectionType = FtpDataConnectionType.PASV;

**Comment by hgupta9** [comment]
Can you try the latest nuget release and report if it still happens?

https://www.nuget.org/packages/FluentFTP/17.0.0

**Comment by hgupta9** [comment]
Closing this since no response received from OP.
