### ISSUE TITLE
Manually resume a file

### ISSUE THREAD

**Issue by tobiasps** [hgupta9/FluentFTP#89]
We have the high level method for uploading files, however if this fails would it not be good to have a method for initiating a resume upload?

In my project I have extended the FtpClient with such a function, it is basically the UploadFileInternal but with with added logic for resume.

```
public bool ResumeFile(Stream fileStream, string remotePath)
{
	return ResumeFileInternal(fileStream, remotePath);
}

private bool ResumeFileInternal(Stream fileData, string remotePath)
{
	Stream upStream = null;

	try
	{
		long offset = 0;

		if (FileExists(remotePath))
		{
			offset = GetFileSize(remotePath);
			if (offset == -1)
				offset = 0; // start from the begining
		}

		// seek to offset
		fileData.Position = offset;

		// open a file connection
		if (offset == 0)
			upStream = OpenWrite(remotePath);
		else
			upStream = OpenAppend(remotePath);

		// loop till entire file uploaded
		long len = fileData.Length;
		byte[] buffer = new byte[TransferChunkSize];
		while (offset < len)
		{
			try
			{

				// read a chunk of bytes from the file
				int readBytes;
				while ((readBytes = fileData.Read(buffer, 0, buffer.Length)) > 0)
				{

					// write chunk to the FTP stream
					upStream.Write(buffer, 0, readBytes);
					upStream.Flush();
					offset += readBytes;
				}

			}
			catch (IOException ex)
			{

				// resume if server disconnects midway (fixes #39)
				if (ex.InnerException != null)
				{
					var iex = ex.InnerException as System.Net.Sockets.SocketException;

					int code = (int)iex.SocketErrorCode;

					int code = iex.ErrorCode;

					if (iex != null && code == 10054)
					{
						upStream.Dispose();
						upStream = OpenAppend(remotePath);
						upStream.Position = offset;
					}
					else throw;
				}
				else throw;

			}
		}

		// wait for while transfer to get over
		while (upStream.Position < upStream.Length)
		{
		}

		// disconnect FTP stream before exiting
		upStream.Dispose();

		// FIX : if this is not added, there appears to be "stale data" on the socket
		// listen for a success/failure reply
		if (!EnableThreadSafeDataConnections)
		{
			FtpReply status = GetReply();
		}

		// fixes #30. the file can have some bytes at the end missing
		// on proxy servers, so we write those missing bytes now.
		if (IsProxy())
		{

			// get the current length of the remote file
			// and check if any bytes are missing
			long curLen = GetFileSize(remotePath);
			if (curLen > 0 && curLen < len && fileData.CanSeek)
			{

				// seek to the point of the local file
				offset = curLen;
				fileData.Position = offset;

				// open the remote file for appending
				upStream = OpenAppend(remotePath, FtpDataType.Binary);
				upStream.Position = offset;

				// read a chunk of bytes from the file
				int readBytes;
				while ((readBytes = fileData.Read(buffer, 0, buffer.Length)) > 0)
				{

					// write chunk to the FTP stream
					upStream.Write(buffer, 0, readBytes);
					upStream.Flush();
					offset += readBytes;
				}

				// disconnect FTP stream before exiting
				upStream.Dispose();

				// FIX : if this is not added, there appears to be "stale data" on the socket
				// listen for a success/failure reply
				if (!EnableThreadSafeDataConnections)
				{
					FtpReply status = GetReply();
				}
			}
		}

		return true;

	}
	catch (Exception ex1)
	{

		// close stream before throwing error
		try
		{
			upStream.Dispose();
		}
		catch (Exception) { }

		// catch errors during upload
		throw new FtpException("Error while uploading the file to the server. See InnerException for more info.", ex1);
	}
}
```

**Comment by hgupta9** [comment]
Great stuff. Do you think its better to have another function or should I add this into UploadFile with an arg for resume?

**Comment by hgupta9** [comment]
Merged with UploadFile methods in the trunk. Thank you for this contribution!

**Comment by hgupta9** [comment]
I will close this when it is released in the next major version FluentFTP 17.0.0

**Comment by tobiasps** [comment]
Looks good @hgupta9, good choice of merging it into UploadFile methods. Thanks!

**Comment by hgupta9** [comment]
Released on nuget. https://www.nuget.org/packages/FluentFTP/17.0.0

**Comment by davidsimmonds** [comment]
Is there a way to have the client resume a failed download? The download would fail if the network went down on either side, typically the client side. I have written an application that uses the most recent FluentFTP library. It starts a download from a FileZilla based server but if the download fails and I use the app to download again it always starts the download from scratch. Is that normal behaviour or do I need to do something special to resume?

**Comment by ildima** [comment]
> Is there a way to have the client resume a failed download? The download would fail if the network went down on either side, typically the client side. I have written an application that uses the most recent FluentFTP library. It starts a download from a FileZilla based server but if the download fails and I use the app to download again it always starts the download from scratch. Is that normal behaviour or do I need to do something special to resume?

Same issue here. I need to download big files (~15Gb each) and in case of whatever issue, I need to download from scratch...

**Comment by robinrodricks** [comment]
There is resume behaviour, but you have to specify the byte index you want
to download from in the OpenRead low level API...

>

**Comment by davidsimmonds** [comment]
I use DownloadFile method to do all of the downloading. I assume by your response that I should use the low level apis in order to download a file or resume a failed download. Is that correct?
