### ISSUE TITLE
Secured connection to FTP

### ISSUE THREAD

**Issue by strejcradis** [hgupta9/FluentFTP#94]
Hi guys,

i need your help with securedly connecting to FTP. When I use Total Commander, i check SSL/TLS and everything works fine, but when i try to configure the same in FluentFTP, it fails on "The remote certificate is invalid according to the validation procedure.".

Please help me how to configure TLS to work like in Total Commander.

My code:

> ftp.Host = hostname;
> ftp.Credentials = new NetworkCredential(username, password);
> ftp.EncryptionMode = FtpEncryptionMode.Explicit;
> ftp.SslProtocols = SslProtocols.Tls;
> ftp.Connect();

My log from Total Commander:

> SSL: Libraries loaded OK! C:\totalcmd\libeay32.dll
> Connect to: (05/09/2017 12:19:36)
> hostname=xx.xx.xx.xx
> username=xxxxxxxx
> startdir=
> xx.xx.xx.xx=xx.xx.xx.xx
> 220 FTP server ready...
> AUTH TLS
> 234 Proceed with negotiation.
> Cert subject: /C=CZ/ST=xxx/L=xxx/CN=xxxxxxxxx
> Cert issuer: /C=CZ/ST=xxx/L=xxx/CN=xxxxxxx
> USER xxxx
> 331 Please specify the password.
> PASS ***********
> 230 Login successful.

I replaced the sensitive data with xxxxxx.

Thanks for you help!!

**Comment by hgupta9** [comment]
You need to set a function that checks if the certificate is valid.
```cs
conn.ValidateCertificate += new FtpSslValidation(OnValidateCertificate);

 void OnValidateCertificate(FtpClient control, FtpSslValidationEventArgs e) {
            e.Accept = true;
}
```
